In [14]:
import pandas as pd

# Load DEG lists without headers
up_genes = pd.read_csv("/usr/users/papantonis1/aman/rnaseq_data/mega_upregulated.tsv", sep="\t", header=None)
down_genes = pd.read_csv("/usr/users/papantonis1/aman/rnaseq_data/mega_downregulated.tsv", sep="\t", header=None)

# Assign column name
up_genes.columns = ["gene_symbol"]
down_genes.columns = ["gene_symbol"]

# Extract gene symbol lists
up_gene_list = up_genes["gene_symbol"].dropna().unique().tolist()
down_gene_list = down_genes["gene_symbol"].dropna().unique().tolist()

# Your list of 56 genes
genes_of_interest = ['NOB1', 'CEACAM5', 'LINC00880', 'BAG3', 'HEXIM1', 'PCBP1', 'TPP1', 'APLP2',
 'ALDH2', 'CTSD', 'CCDC124', 'IL6R', 'LRRC45', 'CDK5RAP3', 'CCNE2', 'HDAC10', 'UVSSA', 'FAT1',
 'MMD', 'SLC30A1', 'CEACAM19', 'PTPRF', 'PODXL', 'INSR', 'ZFP36L2', 'CDCA8', 'BICC1', 'CDCP1',
 'MEI1', 'SORT1', 'CLU', 'MMP24-AS1-EDEM2', 'GAR1', 'FHOD1', 'SLC17A8', 'EFNA5', 'SNORA80B',
 'LAMC2', 'BHLHE40', 'APOBEC3F', 'CASP6', 'SGSM3', 'PARM1', 'IL17RD', 'LTBP1', 'MECOM']

# Remove duplicates
genes_of_interest = list(set(genes_of_interest))

# Classify each gene
def get_deg_status(gene):
    if gene in up_gene_list:
        return "up"
    elif gene in down_gene_list:
        return "down"
    else:
        return "not_deg"

# Build DataFrame
comparison_df = pd.DataFrame({
    "gene_symbol": genes_of_interest,
    "deg_status": [get_deg_status(g) for g in genes_of_interest]
})

# View or export
print(comparison_df.sort_values("deg_status"))
# Optional: comparison_df.to_csv("gene_deg_classification.tsv", sep="\t", index=False)

        gene_symbol deg_status
22            UVSSA       down
23           HDAC10       down
2             MECOM       down
3             CCNE2       down
44            FHOD1       down
39            SGSM3       down
38         SNORA80B       down
19           LRRC45       down
36              MMD       down
18            EFNA5       down
24         CDK5RAP3       down
13            CASP6       down
33            BICC1       down
28         CEACAM19         up
29            PCBP1         up
30            PODXL         up
34            PARM1         up
32          SLC30A1         up
35            CDCA8         up
37            PTPRF         up
40             TPP1         up
41             FAT1         up
42            CDCP1         up
43          BHLHE40         up
31             CTSD         up
27             IL6R         up
0             APLP2         up
25          SLC17A8         up
1             ALDH2         up
4            HEXIM1         up
5           ZFP36L2         up
6             LTBP1         up
7             LAMC2         up
8   MMP24-AS1-EDEM2         up
9              MEI1         up
26          CEACAM5         up
10         APOBEC3F         up
12             BAG3         up
14             GAR1         up
15              CLU         up
16             INSR         up
17           IL17RD         up
20          CCDC124         up
21        LINC00880         up
11            SORT1         up
45             NOB1         up

In [15]:
comparison_df[comparison_df["deg_status"] == "down"]

   gene_symbol deg_status
2        MECOM       down
3        CCNE2       down
13       CASP6       down
18       EFNA5       down
19      LRRC45       down
22       UVSSA       down
23      HDAC10       down
24    CDK5RAP3       down
33       BICC1       down
36         MMD       down
38    SNORA80B       down
39       SGSM3       down
44       FHOD1       down

In [16]:
len(comparison_df[comparison_df["deg_status"] == "down"])

13

In [17]:
comparison_df[comparison_df["deg_status"] == "up"]

        gene_symbol deg_status
0             APLP2         up
1             ALDH2         up
4            HEXIM1         up
5           ZFP36L2         up
6             LTBP1         up
7             LAMC2         up
8   MMP24-AS1-EDEM2         up
9              MEI1         up
10         APOBEC3F         up
11            SORT1         up
12             BAG3         up
14             GAR1         up
15              CLU         up
16             INSR         up
17           IL17RD         up
20          CCDC124         up
21        LINC00880         up
25          SLC17A8         up
26          CEACAM5         up
27             IL6R         up
28         CEACAM19         up
29            PCBP1         up
30            PODXL         up
31             CTSD         up
32          SLC30A1         up
34            PARM1         up
35            CDCA8         up
37            PTPRF         up
40             TPP1         up
41             FAT1         up
42            CDCP1         up
43          BHLHE40         up
45             NOB1         up

In [18]:
len(comparison_df[comparison_df["deg_status"] == "up"])

33