In [1]:
import pandas as pd
from IPython.display import display

In [2]:
gene_loop = pd.read_csv("/usr/users/papantonis1/aman/rnaseq_data/loops_with_gene_info.cleaned.csv", sep=",")
gene_loop

,Unnamed: 0,chr1,start1,end1,chr2,start2,end2,status,ctrl_signal,rbp1_signal,...,E1_anchor1_ctrl,E1_anchor1_rbp1,E1_anchor2_ctrl,E1_anchor2_rbp1,delta_E1_anchor1,delta_E1_anchor2,loop_chr,loop_start,loop_end,gene_id
0,8,chr1,6105000,6110000,chr1,6240000,6245000,shared,NaN,NaN,...,NaN,0.829346,NaN,NaN,NaN,NaN,chr1,6105000,6245000,"ENST00000377939.5,ENST00000463453.1,ENST000004..."
1,29,chr1,9782500,9787500,chr1,9862500,9867500,shared,0.049133,0.038743,...,0.674870,0.842693,0.835179,0.690057,0.167823,-0.145121,chr1,9782500,9867500,"ENST00000361311.4,ENST00000377298.9,ENST000006..."
2,71,chr1,21222500,21227500,chr1,21572500,21577500,shared,0.015427,0.010033,...,0.463574,0.456581,0.598057,0.652091,-0.006993,0.054035,chr1,21222500,21577500,"ENST00000264205.10,ENST00000357071.8,ENST00000..."
3,77,chr1,22665000,22670000,chr1,22960000,22965000,shared,0.025278,0.027536,...,0.587471,0.558545,0.492335,0.536689,-0.028926,0.044354,chr1,22665000,22965000,"ENST00000374627.1,ENST00000374630.8,ENST000003..."
4,78,chr1,22672500,22677500,chr1,22882500,22887500,shared,0.019734,0.030242,...,0.587471,0.558545,0.661385,0.647487,-0.028926,-0.013898,chr1,22672500,22887500,"ENST00000374627.1,ENST00000374630.8,ENST000003..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1245,32165,chr7,51412500,51417500,chr7,55602500,55607500,gained,0.021059,0.011941,...,0.406646,0.454487,0.610640,0.678323,0.047841,0.067683,chr7,51412500,55607500,"ENST00000275493.7,ENST00000342916.7,ENST000003..."
1246,32208,chr8,94812500,94817500,chr8,95022500,95027500,gained,0.012306,0.015876,...,0.040931,0.090414,0.528279,0.409177,0.049483,-0.119102,chr8,94812500,95027500,"ENST00000308108.9,ENST00000396133.7,ENST000005..."
1247,32213,chr8,122735000,122740000,chr8,123060000,123065000,gained,0.005878,0.011803,...,0.580906,0.531595,-0.156556,-0.213083,-0.049312,-0.056527,chr8,122735000,123065000,"ENST00000314393.6,ENST00000521482.5,ENST000005..."
1248,32230,chr9,33582500,33587500,chr9,38552500,38557500,gained,0.040927,0.032843,...,-0.120256,-0.077855,0.011444,-0.040473,0.042401,-0.051918,chr9,33582500,38557500,"ENST00000329305.6,ENST00000378292.9,ENST000004..."
1249,32235,chr9,83842500,83847500,chr9,84262500,84267500,gained,0.008119,0.014589,...,0.797962,0.693939,0.805269,0.697137,-0.104023,-0.108131,chr9,83842500,84267500,"ENST00000297814.7,ENST00000334204.6,ENST000003..."

In [3]:
all=pd.read_csv("/usr/users/papantonis1/aman/microc_project/loop_calling_premade_hic/jupyter_notes/ml_5_multiclassmodel.csv", sep=',')

In [4]:
# fill Nan rows in gene_id col.
gene_loop["gene_id"]=gene_loop["gene_id"].fillna('').astype(str)

In [5]:
# convert into a list ## The gene id col. is now a list
gene_loop["gene_list"]=gene_loop["gene_id"].str.split(',')
gene_loop

,Unnamed: 0,chr1,start1,end1,chr2,start2,end2,status,ctrl_signal,rbp1_signal,...,E1_anchor1_rbp1,E1_anchor2_ctrl,E1_anchor2_rbp1,delta_E1_anchor1,delta_E1_anchor2,loop_chr,loop_start,loop_end,gene_id,gene_list
0,8,chr1,6105000,6110000,chr1,6240000,6245000,shared,NaN,NaN,...,0.829346,NaN,NaN,NaN,NaN,chr1,6105000,6245000,"ENST00000377939.5,ENST00000463453.1,ENST000004...","[ENST00000377939.5, ENST00000463453.1, ENST000..."
1,29,chr1,9782500,9787500,chr1,9862500,9867500,shared,0.049133,0.038743,...,0.842693,0.835179,0.690057,0.167823,-0.145121,chr1,9782500,9867500,"ENST00000361311.4,ENST00000377298.9,ENST000006...","[ENST00000361311.4, ENST00000377298.9, ENST000..."
2,71,chr1,21222500,21227500,chr1,21572500,21577500,shared,0.015427,0.010033,...,0.456581,0.598057,0.652091,-0.006993,0.054035,chr1,21222500,21577500,"ENST00000264205.10,ENST00000357071.8,ENST00000...","[ENST00000264205.10, ENST00000357071.8, ENST00..."
3,77,chr1,22665000,22670000,chr1,22960000,22965000,shared,0.025278,0.027536,...,0.558545,0.492335,0.536689,-0.028926,0.044354,chr1,22665000,22965000,"ENST00000374627.1,ENST00000374630.8,ENST000003...","[ENST00000374627.1, ENST00000374630.8, ENST000..."
4,78,chr1,22672500,22677500,chr1,22882500,22887500,shared,0.019734,0.030242,...,0.558545,0.661385,0.647487,-0.028926,-0.013898,chr1,22672500,22887500,"ENST00000374627.1,ENST00000374630.8,ENST000003...","[ENST00000374627.1, ENST00000374630.8, ENST000..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1245,32165,chr7,51412500,51417500,chr7,55602500,55607500,gained,0.021059,0.011941,...,0.454487,0.610640,0.678323,0.047841,0.067683,chr7,51412500,55607500,"ENST00000275493.7,ENST00000342916.7,ENST000003...","[ENST00000275493.7, ENST00000342916.7, ENST000..."
1246,32208,chr8,94812500,94817500,chr8,95022500,95027500,gained,0.012306,0.015876,...,0.090414,0.528279,0.409177,0.049483,-0.119102,chr8,94812500,95027500,"ENST00000308108.9,ENST00000396133.7,ENST000005...","[ENST00000308108.9, ENST00000396133.7, ENST000..."
1247,32213,chr8,122735000,122740000,chr8,123060000,123065000,gained,0.005878,0.011803,...,0.531595,-0.156556,-0.213083,-0.049312,-0.056527,chr8,122735000,123065000,"ENST00000314393.6,ENST00000521482.5,ENST000005...","[ENST00000314393.6, ENST00000521482.5, ENST000..."
1248,32230,chr9,33582500,33587500,chr9,38552500,38557500,gained,0.040927,0.032843,...,-0.077855,0.011444,-0.040473,0.042401,-0.051918,chr9,33582500,38557500,"ENST00000329305.6,ENST00000378292.9,ENST000004...","[ENST00000329305.6, ENST00000378292.9, ENST000..."
1249,32235,chr9,83842500,83847500,chr9,84262500,84267500,gained,0.008119,0.014589,...,0.693939,0.805269,0.697137,-0.104023,-0.108131,chr9,83842500,84267500,"ENST00000297814.7,ENST00000334204.6,ENST000003...","[ENST00000297814.7, ENST00000334204.6, ENST000..."

In [6]:
# creating a new row for each gene in the df
edges = gene_loop[['loop_id', 'gene_list']].explode('gene_list')

In [7]:
edges = edges[edges['gene_list'] != '']  # Remove blanks

In [8]:
# col structuring for cytoscape
edges.rename(columns={'loop_id': 'source', 'gene_list': 'target'}, inplace=True)
edges['interaction'] = 'loop-gene'
edges

      source             target interaction
0          8  ENST00000377939.5   loop-gene
0          8  ENST00000463453.1   loop-gene
0          8  ENST00000466994.5   loop-gene
0          8  ENST00000483336.1   loop-gene
0          8  ENST00000484435.1   loop-gene
...      ...                ...         ...
1249   32235  ENST00000297814.7   loop-gene
1249   32235  ENST00000334204.6   loop-gene
1249   32235  ENST00000376347.1   loop-gene
1249   32235  ENST00000413982.5   loop-gene
1249   32235  ENST00000495062.2   loop-gene

[10283 rows x 3 columns]

In [9]:
from mygene import MyGeneInfo
mg = MyGeneInfo()

# Extract unique transcript IDs (remove version suffixes)
transcript_ids = edges['target'].str.replace(r'\.\d+$', '', regex=True).unique().tolist()

# Query mygene.info
gene_info = mg.querymany(transcript_ids, scopes='ensembl.transcript', fields='symbol', species='human')

# Build mapping
mapping = {entry['query']: entry.get('symbol', '') for entry in gene_info}

# Apply mapping (strip .X from ENSTs before mapping)
edges['hgnc_symbol'] = edges['target'].str.replace(r'\.\d+$', '', regex=True).map(mapping)

Input sequence provided is already in string format. No operation performed
Input sequence provided is already in string format. No operation performed
1 input query terms found no hit:	['ENST00000316528']

In [10]:
edges['target'] = edges['hgnc_symbol']
edges.drop(columns=['hgnc_symbol'], inplace=True)
edges

      source  target interaction
0          8  RNF207   loop-gene
0          8  RNF207   loop-gene
0          8  RNF207   loop-gene
0          8  RNF207   loop-gene
0          8  RNF207   loop-gene
...      ...     ...         ...
1249   32235   KIF27   loop-gene
1249   32235   KIF27   loop-gene
1249   32235   KIF27   loop-gene
1249   32235   KIF27   loop-gene
1249   32235   KIF27   loop-gene

[10283 rows x 3 columns]

In [11]:
edges.drop_duplicates(subset=['source', 'target'], inplace=True)
edges['target'].replace('', pd.NA, inplace=True)
edges['interaction'].replace('', pd.NA, inplace=True)
edges.dropna(inplace=True)
edges

/tmp/ipykernel_1774131/1236572071.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  edges['target'].replace('', pd.NA, inplace=True)
/tmp/ipykernel_1774131/1236572071.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  edges['interaction'].replace('', pd.NA, inplace=True)

      source  target interaction
0          8  RNF207   loop-gene
1         29  CLSTN1   loop-gene
2         71    ECE1   loop-gene
3         77   EPHB2   loop-gene
4         78   EPHB2   loop-gene
...      ...     ...         ...
1245   32165    EGFR   loop-gene
1246   32208   CCNE2   loop-gene
1247   32213    ZHX2   loop-gene
1248   32230    TPM2   loop-gene
1249   32235   KIF27   loop-gene

[1330 rows x 3 columns]

In [12]:
# checking
print("Unique loops (source nodes):", edges['source'].nunique())

Unique loops (source nodes): 1250

In [13]:
edges.to_csv('cytoscape_input.csv', sep=',', index=False)

In [14]:
def checkloopid(x, path):
    datatable=[]
    #y = path[path["loop_id"] == x]
    for i in x:
        datatable.append(path[path["loop_id"] == i])
    return display(pd.concat(datatable, ignore_index=True))

In [15]:
checkloopid([8, 15103], gene_loop)

,Unnamed: 0,chr1,start1,end1,chr2,start2,end2,status,ctrl_signal,rbp1_signal,...,E1_anchor1_rbp1,E1_anchor2_ctrl,E1_anchor2_rbp1,delta_E1_anchor1,delta_E1_anchor2,loop_chr,loop_start,loop_end,gene_id,gene_list
0,8,chr1,6105000,6110000,chr1,6240000,6245000,shared,NaN,NaN,...,0.829346,NaN,NaN,NaN,NaN,chr1,6105000,6245000,"ENST00000377939.5,ENST00000463453.1,ENST000004...","[ENST00000377939.5, ENST00000463453.1, ENST000..."
1,15103,chr1,6195000,6200000,chr1,6235000,6240000,lost,0.061147,0.046581,...,0.477021,0.742294,0.759093,-0.014879,0.016799,chr1,6195000,6240000,"ENST00000377939.5,ENST00000463453.1,ENST000004...","[ENST00000377939.5, ENST00000463453.1, ENST000..."

In [28]:
y = "816 817 818 819 8302 8303 8304 8305 8306 8307 8308 8309 15409 15410 18309 20003 20004 20005 20006 20007 28240 28241 28242" # gene here is BICC1
y = list(map(int, y.split()))
checkloopid(y, gene_loop)

,Unnamed: 0,chr1,start1,end1,chr2,start2,end2,status,ctrl_signal,rbp1_signal,...,E1_anchor1_rbp1,E1_anchor2_ctrl,E1_anchor2_rbp1,delta_E1_anchor1,delta_E1_anchor2,loop_chr,loop_start,loop_end,gene_id,gene_list
0,816,chr10,58412500,58417500,chr10,58532500,58537500,shared,0.014086,0.015996,...,0.626709,0.757136,0.806235,-0.027295,0.049098,chr10,58412500,58537500,ENST00000373886.8,[ENST00000373886.8]
1,817,chr10,58775000,58780000,chr10,59225000,59230000,shared,0.012999,0.013169,...,0.600326,0.829062,0.845977,-0.081868,0.016915,chr10,58775000,59230000,"ENST00000263103.1,ENST00000373886.8","[ENST00000263103.1, ENST00000373886.8]"
2,818,chr10,58780000,58785000,chr10,59620000,59625000,shared,0.013499,0.013092,...,0.731312,0.743941,0.703397,0.015009,-0.040544,chr10,58780000,59625000,"ENST00000263103.1,ENST00000373886.8","[ENST00000263103.1, ENST00000373886.8]"
3,819,chr10,58782500,58787500,chr10,59172500,59177500,shared,0.014680,0.010119,...,0.702147,0.821204,0.857791,-0.015055,0.036587,chr10,58782500,59177500,"ENST00000263103.1,ENST00000373886.8","[ENST00000263103.1, ENST00000373886.8]"
4,8302,chr10,58412500,58417500,chr10,58512500,58517500,lost,0.010063,0.015774,...,0.838770,0.839411,0.876881,-0.054225,0.037469,chr10,58412500,58517500,ENST00000373886.8,[ENST00000373886.8]
5,8303,chr10,58532500,58537500,chr10,59182500,59187500,lost,0.005691,0.004256,...,0.745805,0.734365,0.748539,0.029702,0.014173,chr10,58532500,59187500,"ENST00000263103.1,ENST00000373886.8,ENST000004...","[ENST00000263103.1, ENST00000373886.8, ENST000..."
6,8304,chr10,58772500,58777500,chr10,58942500,58947500,lost,0.007564,0.005177,...,0.748539,0.831118,0.870622,0.014173,0.039504,chr10,58772500,58947500,"ENST00000263103.1,ENST00000373886.8","[ENST00000263103.1, ENST00000373886.8]"
7,8305,chr10,58775000,58780000,chr10,59110000,59115000,lost,0.006417,0.003294,...,0.748539,0.851831,0.884751,0.014173,0.032920,chr10,58775000,59115000,"ENST00000263103.1,ENST00000373886.8","[ENST00000263103.1, ENST00000373886.8]"
8,8306,chr10,58782500,58787500,chr10,60052500,60057500,lost,0.001322,0.001802,...,1.066774,1.177627,1.068759,-0.065053,-0.108869,chr10,58782500,60057500,"ENST00000263103.1,ENST00000373886.8","[ENST00000263103.1, ENST00000373886.8]"
9,8307,chr10,58785000,58790000,chr10,58915000,58920000,lost,0.010040,0.009637,...,1.066774,0.851831,0.884751,-0.065053,0.032920,chr10,58785000,58920000,"ENST00000263103.1,ENST00000373886.8","[ENST00000263103.1, ENST00000373886.8]"
10,8308,chr10,58790000,58795000,chr10,58850000,58855000,lost,0.017176,0.010003,...,0.870622,0.647502,0.658689,0.039504,0.011187,chr10,58790000,58855000,"ENST00000263103.1,ENST00000373886.8","[ENST00000263103.1, ENST00000373886.8]"
11,8309,chr10,58802500,58807500,chr10,58922500,58927500,lost,0.012221,0.012751,...,0.658689,0.546070,0.535469,0.011187,-0.010601,chr10,58802500,58927500,"ENST00000263103.1,ENST00000373886.8","[ENST00000263103.1, ENST00000373886.8]"
12,15409,chr10,58412500,58417500,chr10,58632500,58637500,lost,0.014808,0.006447,...,0.071778,0.106077,0.079049,0.033938,-0.027029,chr10,58412500,58637500,"ENST00000373886.8,ENST00000476684.1","[ENST00000373886.8, ENST00000476684.1]"
13,15410,chr10,58782500,58787500,chr10,59602500,59607500,lost,0.004372,0.002461,...,-1.162869,-1.153871,-1.273031,0.047319,-0.119161,chr10,58782500,59607500,"ENST00000263103.1,ENST00000373886.8","[ENST00000263103.1, ENST00000373886.8]"
14,18309,chr10,58530000,58535000,chr10,58635000,58640000,lost,0.015134,0.011772,...,-0.158552,-0.328604,-0.258224,0.043954,0.070380,chr10,58530000,58640000,"ENST00000373886.8,ENST00000476684.1","[ENST00000373886.8, ENST00000476684.1]"
15,20003,chr10,58410000,58415000,chr10,58525000,58530000,gained,0.015076,0.013221,...,-0.158949,0.001674,-0.044828,-0.003017,-0.046502,chr10,58410000,58530000,ENST00000373886.8,[ENST00000373886.8]
16,20004,chr10,58412500,58417500,chr10,58642500,58647500,gained,0.010599,0.008508,...,-0.158949,-0.065307,0.062579,-0.003017,0.127887,chr10,58412500,58647500,"ENST00000373886.8,ENST00000476684.1","[ENST00000373886.8, ENST00000476684.1]"
17,20005,chr10,58530000,58535000,chr10,58645000,58650000,gained,0.012069,0.015382,...,-0.044828,0.092663,0.038049,-0.046502,-0.054614,chr10,58530000,58650000,"ENST00000373886.8,ENST00000476684.1","[ENST00000373886.8, ENST00000476684.1]"
18,20006,chr10,58780000,58785000,chr10,59225000,59230000,gained,0.013258,0.012500,...,-0.044828,0.062184,0.036794,-0.046502,-0.025390,chr10,58780000,59230000,"ENST00000263103.1,ENST00000373886.8","[ENST00000263103.1, ENST00000373886.8]"
19,20007,chr10,58780000,58785000,chr10,59180000,59185000,gained,0.028276,0.019463,...,0.036794,0.092663,0.038049,-0.025390,-0.054614,chr10,58780000,59185000,"ENST00000263103.1,ENST00000373886.8","[ENST00000263103.1, ENST00000373886.8]"
20,28240,chr10,58782500,58787500,chr10,59612500,59617500,gained,0.007511,0.009312,...,0.288247,0.231800,0.321466,-0.012136,0.089666,chr10,58782500,59617500,"ENST00000263103.1,ENST00000373886.8","[ENST00000263103.1, ENST00000373886.8]"
21,28241,chr10,58782500,58787500,chr10,60032500,60037500,gained,0.002086,0.002214,...,0.288247,0.448452,0.417288,-0.012136,-0.031164,chr10,58782500,60037500,"ENST00000263103.1,ENST00000373886.8","[ENST00000263103.1, ENST00000373886.8]"
22,28242,chr10,58792500,58797500,chr10,58942500,58947500,gained,0.011325,0.013516,...,0.288247,0.242772,0.209183,-0.012136,-0.033589,chr10,58792500,58947500,"ENST00000263103.1,ENST00000373886.8","[ENST00000263103.1, ENST00000373886.8]"

In [29]:
checkloopid(y, all)

,Unnamed: 0,chr1,start1,end1,chr2,start2,end2,status,ctrl_signal,rbp1_signal,...,H3K4me3_signal,rad21_signal,GC_mean,GC_diff,E1_anchor1_ctrl,E1_anchor1_rbp1,E1_anchor2_ctrl,E1_anchor2_rbp1,delta_E1_anchor1,delta_E1_anchor2
0,816,chr10,58412500,58417500,chr10,58532500,58537500,shared,0.014086,0.015996,...,0.375541,0.038777,0.3930,0.0952,0.654004,0.626709,0.757136,0.806235,-0.027295,0.049098
1,817,chr10,58775000,58780000,chr10,59225000,59230000,shared,0.012999,0.013169,...,0.188543,0.057805,0.3557,0.0542,0.682193,0.600326,0.829062,0.845977,-0.081868,0.016915
2,818,chr10,58780000,58785000,chr10,59620000,59625000,shared,0.013499,0.013092,...,0.203748,0.061077,0.4033,0.0586,0.716303,0.731312,0.743941,0.703397,0.015009,-0.040544
3,819,chr10,58782500,58787500,chr10,59172500,59177500,shared,0.014680,0.010119,...,0.527973,0.047640,0.4086,0.1008,0.717202,0.702147,0.821204,0.857791,-0.015055,0.036587
4,8302,chr10,58412500,58417500,chr10,58512500,58517500,lost,0.010063,0.015774,...,0.188543,0.033289,0.4381,0.0050,0.892994,0.838770,0.839411,0.876881,-0.054225,0.037469
5,8303,chr10,58532500,58537500,chr10,59182500,59187500,lost,0.005691,0.004256,...,0.188543,0.043466,0.3665,0.0422,0.716102,0.745805,0.734365,0.748539,0.029702,0.014173
6,8304,chr10,58772500,58777500,chr10,58942500,58947500,lost,0.007564,0.005177,...,0.188543,0.044639,0.3882,0.0176,0.734365,0.748539,0.831118,0.870622,0.014173,0.039504
7,8305,chr10,58775000,58780000,chr10,59110000,59115000,lost,0.006417,0.003294,...,0.188543,0.026284,0.3622,0.0412,0.734365,0.748539,0.851831,0.884751,0.014173,0.032920
8,8306,chr10,58782500,58787500,chr10,60052500,60057500,lost,0.001322,0.001802,...,0.188543,0.024209,0.3649,0.0134,1.131828,1.066774,1.177627,1.068759,-0.065053,-0.108869
9,8307,chr10,58785000,58790000,chr10,58915000,58920000,lost,0.010040,0.009637,...,0.202010,0.024054,0.3698,0.0264,1.131828,1.066774,0.851831,0.884751,-0.065053,0.032920
10,8308,chr10,58790000,58795000,chr10,58850000,58855000,lost,0.017176,0.010003,...,0.216099,0.024107,0.3989,0.0262,0.831118,0.870622,0.647502,0.658689,0.039504,0.011187
11,8309,chr10,58802500,58807500,chr10,58922500,58927500,lost,0.012221,0.012751,...,0.188543,0.024547,0.3646,0.0000,0.647502,0.658689,0.546070,0.535469,0.011187,-0.010601
12,15409,chr10,58412500,58417500,chr10,58632500,58637500,lost,0.014808,0.006447,...,0.198011,0.042098,0.4051,0.0710,0.037840,0.071778,0.106077,0.079049,0.033938,-0.027029
13,15410,chr10,58782500,58787500,chr10,59602500,59607500,lost,0.004372,0.002461,...,0.243210,0.041130,0.3872,0.0580,-1.210188,-1.162869,-1.153871,-1.273031,0.047319,-0.119161
14,18309,chr10,58530000,58535000,chr10,58635000,58640000,lost,0.015134,0.011772,...,0.208157,0.025642,0.3718,0.0216,-0.202506,-0.158552,-0.328604,-0.258224,0.043954,0.070380
15,20003,chr10,58410000,58415000,chr10,58525000,58530000,gained,0.015076,0.013221,...,0.191236,0.056913,0.3995,0.0486,-0.155933,-0.158949,0.001674,-0.044828,-0.003017,-0.046502
16,20004,chr10,58412500,58417500,chr10,58642500,58647500,gained,0.010599,0.008508,...,0.234679,0.026339,0.4078,0.0656,-0.155933,-0.158949,-0.065307,0.062579,-0.003017,0.127887
17,20005,chr10,58530000,58535000,chr10,58645000,58650000,gained,0.012069,0.015382,...,0.188543,0.034727,0.3721,0.0222,0.001674,-0.044828,0.092663,0.038049,-0.046502,-0.054614
18,20006,chr10,58780000,58785000,chr10,59225000,59230000,gained,0.013258,0.012500,...,0.219105,0.044002,0.3513,0.0454,0.001674,-0.044828,0.062184,0.036794,-0.046502,-0.025390
19,20007,chr10,58780000,58785000,chr10,59180000,59185000,gained,0.028276,0.019463,...,0.629226,0.028724,0.3586,0.0308,0.062184,0.036794,0.092663,0.038049,-0.025390,-0.054614
20,28240,chr10,58782500,58787500,chr10,59612500,59617500,gained,0.007511,0.009312,...,0.404512,0.029090,0.3927,0.0690,0.300383,0.288247,0.231800,0.321466,-0.012136,0.089666
21,28241,chr10,58782500,58787500,chr10,60032500,60037500,gained,0.002086,0.002214,...,0.188543,0.025986,0.3854,0.0544,0.300383,0.288247,0.448452,0.417288,-0.012136,-0.031164
22,28242,chr10,58792500,58797500,chr10,58942500,58947500,gained,0.011325,0.013516,...,0.188543,0.032917,0.3887,0.0166,0.300383,0.288247,0.242772,0.209183,-0.012136,-0.033589