## Gene-level TSS

In [1]:
library(AnnotationDbi)
library(org.Hs.eg.db)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
library(dplyr)
library(rtracklayer)

Loading required package: stats4

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which.max, which.min


Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.


Loading required package: IRanges

Loading required package: S4Vectors


Attaching package: ‘S4Vectors’


The following object is masked from ‘package:utils’:

    findMatches


The following objects are masked from ‘package:base’:

    expand.grid, I, unname




Loading required package: GenomicFeatures

Loading required package: GenomeInfoDb

Loading required package: GenomicRanges


Attaching package: ‘dplyr’


The following objects are masked from ‘package:GenomicRanges’:

    intersect, setdiff, union


The following object is masked from ‘package:GenomeInfoDb’:

    intersect


The following object is masked from ‘package:AnnotationDbi’:

    select


The following objects are masked from ‘package:IRanges’:

    collapse, desc, intersect, setdiff, slice, union


The following objects are masked from ‘package:S4Vectors’:

    first, intersect, rename, setdiff, setequal, union


The following object is masked from ‘package:Biobase’:

    combine


The following objects are masked from ‘package:BiocGenerics’:

    combine, intersect, setdiff, union


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [2]:
# Load gene symbols
candidate_genes <- read.delim("/usr/users/papantonis1/aman/rnaseq_data/mega_upregulated.tsv", header = FALSE)[[1]]

In [3]:
# Map gene symbols to Entrez IDs
entrez_ids <- mapIds(org.Hs.eg.db,
                     keys = candidate_genes,
                     column = "ENTREZID",
                     keytype = "SYMBOL",
                     multiVals = "first")

'select()' returned 1:1 mapping between keys and columns

In [4]:
# Get TSS from TxDb
tss_coords <- genes(TxDb.Hsapiens.UCSC.hg38.knownGene)

  2135 genes were dropped because they have exons located on both strands
  of the same reference sequence or on more than one reference sequence,
  so cannot be represented by a single genomic range.
  Use 'single.strand.genes.only=FALSE' to get all the genes in a
  GRangesList object, or use suppressMessages() to suppress this message.

In [5]:
# Filter for my genes only here
tss_subset <- tss_coords[tss_coords$gene_id %in% entrez_ids]

In [6]:
# Extract TSS as GRanges object
tss_ranges <- promoters(tss_subset, upstream = 0, downstream = 1)

In [7]:
tss_ranges

GRanges object with 190 ranges and 1 metadata column:
            seqnames    ranges strand |     gene_id
               <Rle> <IRanges>  <Rle> | <character>
       1001    chr16  68644993      + |        1001
  100131378    chr11  33722448      - |   100131378
  100652740    chr16  31201885      + |   100652740
      10112     chr5 138178719      + |       10112
      10262     chr1 149927803      - |       10262
        ...      ...       ...    ... .         ...
       9601     chr7 149028662      - |        9601
       9672     chr1  30908758      - |        9672
        976    chr19  14380501      + |         976
        991     chr1  43358981      + |         991
       9918    chr12   6493356      + |        9918
  -------
  seqinfo: 711 sequences (1 circular) from hg38 genome

In [8]:
# add name column
mcols(tss_ranges)$name <- mcols(tss_ranges)$gene_id

#Add score column
mcols(tss_ranges)$score <- 0

# Export as BED
export(tss_ranges, "mega_upregulated_TSS.bed", format = "BED")

In [9]:
# promoter - motif or TF binding
tss_core_promoter <- promoters(tss_subset, upstream = 2000, downstream = 500)
# add name column
mcols(tss_core_promoter)$name <- mcols(tss_core_promoter)$gene_id

#Add score column
mcols(tss_core_promoter)$score <- 0

# Export as BED
export(tss_core_promoter, "mega_upregulated_corePromoter.bed", format = "BED")

In [10]:
# to do - for down regulated

In [11]:
# Load gene symbols
candidate_genes <- read.delim("/usr/users/papantonis1/aman/rnaseq_data/mega_downregulated.tsv", header = FALSE)[[1]]

In [12]:
# Map gene symbols to Entrez IDs
entrez_ids <- mapIds(org.Hs.eg.db,
                     keys = candidate_genes,
                     column = "ENTREZID",
                     keytype = "SYMBOL",
                     multiVals = "first")

'select()' returned 1:1 mapping between keys and columns

In [13]:
# Get TSS from TxDb
tss_coords <- genes(TxDb.Hsapiens.UCSC.hg38.knownGene)

  2135 genes were dropped because they have exons located on both strands
  of the same reference sequence or on more than one reference sequence,
  so cannot be represented by a single genomic range.
  Use 'single.strand.genes.only=FALSE' to get all the genes in a
  GRangesList object, or use suppressMessages() to suppress this message.

In [14]:
# Filter for my genes only here
tss_subset <- tss_coords[tss_coords$gene_id %in% entrez_ids]

In [15]:
# Extract TSS as GRanges object
tss_ranges <- promoters(tss_subset, upstream = 0, downstream = 1)

In [16]:
# add name column
mcols(tss_ranges)$name <- mcols(tss_ranges)$gene_id

#Add score column
mcols(tss_ranges)$score <- 0

# Export as BED
export(tss_ranges, "mega_downregulated_TSS.bed", format = "BED")

---

## Transcript -level TSS

##### first up regulated

In [17]:
mygenes <- read.delim("/usr/users/papantonis1/aman/rnaseq_data/mega_upregulated.tsv", header = FALSE)[[1]]

In [18]:
library(org.Hs.eg.db)

# Map gene symbols to Entrez IDs
mapped <- mapIds(org.Hs.eg.db,
                 keys = mygenes,
                 column = "ENTREZID",
                 keytype = "SYMBOL",
                 multiVals = "first")

# Remove NAs
entrez_ids <- na.omit(mapped)

'select()' returned 1:1 mapping between keys and columns

In [19]:
txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene
mygenes.transcripts <- subset(
  transcripts(txdb, columns = c("tx_id", "tx_name", "gene_id")),
  gene_id %in% entrez_ids
)

In [20]:
mygenes.tss <- resize(mygenes.transcripts, width=1, fix="start")

In [21]:
as.data.frame(mygenes.tss) # TSS position per transcript only

     seqnames             start    end      width strand tx_id
1    chr1                 11934205 11934205 1     +       955
2    chr1                 11934694 11934694 1     +       956
3    chr1                 11934717 11934717 1     +       957
4    chr1                 11934734 11934734 1     +       958
5    chr1                 11934743 11934743 1     +       959
6    chr1                 11954301 11954301 1     +       960
7    chr1                 11964688 11964688 1     +       961
8    chr1                 11964702 11964702 1     +       962
9    chr1                 11971543 11971543 1     +       963
10   chr1                 22710839 22710839 1     +      1566
11   chr1                 22710839 22710839 1     +      1567
12   chr1                 22710965 22710965 1     +      1568
13   chr1                 22710970 22710970 1     +      1569
14   chr1                 22775178 22775178 1     +      1571
15   chr1                 22800240 22800240 1     +      1572
16   chr1                 22865159 22865159 1     +      1573
17   chr1                 28369582 28369582 1     +      2093
18   chr1                 28369609 28369609 1     +      2094
19   chr1                 28369710 28369710 1     +      2095
20   chr1                 28369739 28369739 1     +      2096
21   chr1                 28369740 28369740 1     +      2097
22   chr1                 28369744 28369744 1     +      2098
23   chr1                 28438151 28438151 1     +      2099
24   chr1                 28438171 28438171 1     +      2100
25   chr1                 28491695 28491695 1     +      2103
26   chr1                 37692481 37692481 1     +      2670
27   chr1                 37692516 37692516 1     +      2671
28   chr1                 43358981 43358981 1     +      3136
29   chr1                 43359013 43359013 1     +      3137
30   chr1                 43359767 43359767 1     +      3138
⋮    ⋮                    ⋮        ⋮        ⋮     ⋮      ⋮
2718 chr17_MU273379v1_fix 126300   126300   1     +      274036
2719 chr17_MU273379v1_fix 126303   126303   1     +      274037
2720 chr17_MU273379v1_fix 135708   135708   1     +      274038
2721 chr17_MU273379v1_fix 136439   136439   1     +      274039
2722 chr17_MU273379v1_fix 137090   137090   1     +      274040
2723 chr17_MU273379v1_fix 141532   141532   1     +      274041
2724 chr2_KQ983256v1_alt  388301   388301   1     +      275096
2725 chr2_KQ983256v1_alt  388327   388327   1     +      275097
2726 chr2_KQ983256v1_alt  388631   388631   1     +      275098
2727 chr2_KQ983256v1_alt  388648   388648   1     +      275099
2728 chr2_KQ983256v1_alt  388648   388648   1     +      275100
2729 chr2_KQ983256v1_alt  388648   388648   1     +      275101
2730 chr2_KQ983256v1_alt  388682   388682   1     +      275102
2731 chr2_KQ983256v1_alt  389352   389352   1     +      275103
2732 chr2_KQ983256v1_alt  393198   393198   1     +      275104
2733 chr2_KQ983256v1_alt  405701   405701   1     +      275105
2734 chrX_MU273395v1_alt  446157   446157   1     +      276624
2735 chrX_MU273395v1_alt  446187   446187   1     +      276625
2736 chrX_MU273395v1_alt  446253   446253   1     +      276626
2737 chrX_MU273395v1_alt  513257   513257   1     +      276627
2738 chrX_MU273395v1_alt  529632   529632   1     +      276628
2739 chrX_MU273395v1_alt  529632   529632   1     +      276629
2740 chrX_MU273395v1_alt  529643   529643   1     +      276630
2741 chrX_MU273395v1_alt  529680   529680   1     +      276631
2742 chrX_MU273395v1_alt  529680   529680   1     +      276632
2743 chrX_MU273395v1_alt  529680   529680   1     +      276633
2744 chrX_MU273395v1_alt  533055   533055   1     +      276634
2745 chrX_MU273395v1_alt  535539   535539   1     +      276635
2746 chrX_MU273395v1_alt  535897   535897   1     +      276636
2747 chrX_MU273395v1_alt  556891   556891   1     +      276637
     tx_name            gene_id
1    ENST00000485046.5   5351
2    ENST00000449038.5   5351
3    ENST00000196061.5   5351
4    ENST00000358133.5   5351
5    ENST00000429000.6   5351
6    ENST00000465920.1   5351
7    ENST00000491536.5   5351
8    ENST00000470133.1   5351
9    ENST00000481933.1   5351
10   ENST00000544305.5   2048
11   ENST00000374630.8   2048
12   ENST00000400191.7   2048
13   ENST00000374632.7   2048
14   ENST00000374627.1   2048
15   ENST00000465676.1   2048
16   ENST00000490436.1   2048
17   ENST00000633371.1  65979
18   ENST00000632202.1  65979
19   ENST00000632421.1  65979
20   ENST00000463428.5  65979
21   ENST00000373839.8  65979
22   ENST00000493669.2  65979
23   ENST00000633167.1  65979
24   ENST00000373836.4  65979
25   ENST00000632964.1  65979
26   ENST00000327331.2  55143
27   ENST00000373055.6  55143
28   ENST00000310955.11   991
29   ENST00000372462.1    991
30   ENST00000478882.1    991
⋮    ⋮                  ⋮
2718 ENST00000707781.1   2548
2719 ENST00000707782.1   2548
2720 ENST00000707783.1   2548
2721 ENST00000707784.1   2548
2722 ENST00000707785.1   2548
2723 ENST00000707786.1   2548
2724 ENST00000636761.3  57683
2725 ENST00000649768.1  57683
2726 ENST00000648555.1  57683
2727 ENST00000648142.1  57683
2728 ENST00000650133.1  57683
2729 ENST00000648655.1  57683
2730 ENST00000649010.1  57683
2731 ENST00000648496.1  57683
2732 ENST00000649836.1  57683
2733 ENST00000637549.1  57683
2734 ENST00000709998.1  50814
2735 ENST00000709999.1  50814
2736 ENST00000710000.1  50814
2737 ENST00000710010.1   7739
2738 ENST00000710011.1   7739
2739 ENST00000710012.1   7739
2740 ENST00000710013.1   7739
2741 ENST00000710014.1   7739
2742 ENST00000710015.1   7739
2743 ENST00000710016.1   7739
2744 ENST00000710017.1   7739
2745 ENST00000710018.1   7739
2746 ENST00000710019.1   7739
2747 ENST00000710020.1   7739

In [22]:
# Converting to dataframe
tss_df <- as.data.frame(mygenes.tss)

# Creating a .bed like table
bed_tss_df <- data.frame(
  chrom = tss_df$seqnames,
  chromStart = tss_df$start - 1,  # BED is 0-based
  chromEnd = tss_df$start,        # 1 bp region
  name = tss_df$tx_name,          
  score = 0,                      # just a standard
  strand = tss_df$strand
)

# Export to BED
write.table(bed_tss_df, file = "upregulated_transcript_level_TSS.bed",
            sep = "\t", quote = FALSE, row.names = FALSE, col.names = FALSE)

In [23]:
tss_df

     seqnames             start    end      width strand tx_id
1    chr1                 11934205 11934205 1     +       955
2    chr1                 11934694 11934694 1     +       956
3    chr1                 11934717 11934717 1     +       957
4    chr1                 11934734 11934734 1     +       958
5    chr1                 11934743 11934743 1     +       959
6    chr1                 11954301 11954301 1     +       960
7    chr1                 11964688 11964688 1     +       961
8    chr1                 11964702 11964702 1     +       962
9    chr1                 11971543 11971543 1     +       963
10   chr1                 22710839 22710839 1     +      1566
11   chr1                 22710839 22710839 1     +      1567
12   chr1                 22710965 22710965 1     +      1568
13   chr1                 22710970 22710970 1     +      1569
14   chr1                 22775178 22775178 1     +      1571
15   chr1                 22800240 22800240 1     +      1572
16   chr1                 22865159 22865159 1     +      1573
17   chr1                 28369582 28369582 1     +      2093
18   chr1                 28369609 28369609 1     +      2094
19   chr1                 28369710 28369710 1     +      2095
20   chr1                 28369739 28369739 1     +      2096
21   chr1                 28369740 28369740 1     +      2097
22   chr1                 28369744 28369744 1     +      2098
23   chr1                 28438151 28438151 1     +      2099
24   chr1                 28438171 28438171 1     +      2100
25   chr1                 28491695 28491695 1     +      2103
26   chr1                 37692481 37692481 1     +      2670
27   chr1                 37692516 37692516 1     +      2671
28   chr1                 43358981 43358981 1     +      3136
29   chr1                 43359013 43359013 1     +      3137
30   chr1                 43359767 43359767 1     +      3138
⋮    ⋮                    ⋮        ⋮        ⋮     ⋮      ⋮
2718 chr17_MU273379v1_fix 126300   126300   1     +      274036
2719 chr17_MU273379v1_fix 126303   126303   1     +      274037
2720 chr17_MU273379v1_fix 135708   135708   1     +      274038
2721 chr17_MU273379v1_fix 136439   136439   1     +      274039
2722 chr17_MU273379v1_fix 137090   137090   1     +      274040
2723 chr17_MU273379v1_fix 141532   141532   1     +      274041
2724 chr2_KQ983256v1_alt  388301   388301   1     +      275096
2725 chr2_KQ983256v1_alt  388327   388327   1     +      275097
2726 chr2_KQ983256v1_alt  388631   388631   1     +      275098
2727 chr2_KQ983256v1_alt  388648   388648   1     +      275099
2728 chr2_KQ983256v1_alt  388648   388648   1     +      275100
2729 chr2_KQ983256v1_alt  388648   388648   1     +      275101
2730 chr2_KQ983256v1_alt  388682   388682   1     +      275102
2731 chr2_KQ983256v1_alt  389352   389352   1     +      275103
2732 chr2_KQ983256v1_alt  393198   393198   1     +      275104
2733 chr2_KQ983256v1_alt  405701   405701   1     +      275105
2734 chrX_MU273395v1_alt  446157   446157   1     +      276624
2735 chrX_MU273395v1_alt  446187   446187   1     +      276625
2736 chrX_MU273395v1_alt  446253   446253   1     +      276626
2737 chrX_MU273395v1_alt  513257   513257   1     +      276627
2738 chrX_MU273395v1_alt  529632   529632   1     +      276628
2739 chrX_MU273395v1_alt  529632   529632   1     +      276629
2740 chrX_MU273395v1_alt  529643   529643   1     +      276630
2741 chrX_MU273395v1_alt  529680   529680   1     +      276631
2742 chrX_MU273395v1_alt  529680   529680   1     +      276632
2743 chrX_MU273395v1_alt  529680   529680   1     +      276633
2744 chrX_MU273395v1_alt  533055   533055   1     +      276634
2745 chrX_MU273395v1_alt  535539   535539   1     +      276635
2746 chrX_MU273395v1_alt  535897   535897   1     +      276636
2747 chrX_MU273395v1_alt  556891   556891   1     +      276637
     tx_name            gene_id
1    ENST00000485046.5   5351
2    ENST00000449038.5   5351
3    ENST00000196061.5   5351
4    ENST00000358133.5   5351
5    ENST00000429000.6   5351
6    ENST00000465920.1   5351
7    ENST00000491536.5   5351
8    ENST00000470133.1   5351
9    ENST00000481933.1   5351
10   ENST00000544305.5   2048
11   ENST00000374630.8   2048
12   ENST00000400191.7   2048
13   ENST00000374632.7   2048
14   ENST00000374627.1   2048
15   ENST00000465676.1   2048
16   ENST00000490436.1   2048
17   ENST00000633371.1  65979
18   ENST00000632202.1  65979
19   ENST00000632421.1  65979
20   ENST00000463428.5  65979
21   ENST00000373839.8  65979
22   ENST00000493669.2  65979
23   ENST00000633167.1  65979
24   ENST00000373836.4  65979
25   ENST00000632964.1  65979
26   ENST00000327331.2  55143
27   ENST00000373055.6  55143
28   ENST00000310955.11   991
29   ENST00000372462.1    991
30   ENST00000478882.1    991
⋮    ⋮                  ⋮
2718 ENST00000707781.1   2548
2719 ENST00000707782.1   2548
2720 ENST00000707783.1   2548
2721 ENST00000707784.1   2548
2722 ENST00000707785.1   2548
2723 ENST00000707786.1   2548
2724 ENST00000636761.3  57683
2725 ENST00000649768.1  57683
2726 ENST00000648555.1  57683
2727 ENST00000648142.1  57683
2728 ENST00000650133.1  57683
2729 ENST00000648655.1  57683
2730 ENST00000649010.1  57683
2731 ENST00000648496.1  57683
2732 ENST00000649836.1  57683
2733 ENST00000637549.1  57683
2734 ENST00000709998.1  50814
2735 ENST00000709999.1  50814
2736 ENST00000710000.1  50814
2737 ENST00000710010.1   7739
2738 ENST00000710011.1   7739
2739 ENST00000710012.1   7739
2740 ENST00000710013.1   7739
2741 ENST00000710014.1   7739
2742 ENST00000710015.1   7739
2743 ENST00000710016.1   7739
2744 ENST00000710017.1   7739
2745 ENST00000710018.1   7739
2746 ENST00000710019.1   7739
2747 ENST00000710020.1   7739

In [24]:
bed_tss_df

     chrom                chromStart chromEnd name               score strand
1    chr1                 11934204   11934205 ENST00000485046.5  0     +
2    chr1                 11934693   11934694 ENST00000449038.5  0     +
3    chr1                 11934716   11934717 ENST00000196061.5  0     +
4    chr1                 11934733   11934734 ENST00000358133.5  0     +
5    chr1                 11934742   11934743 ENST00000429000.6  0     +
6    chr1                 11954300   11954301 ENST00000465920.1  0     +
7    chr1                 11964687   11964688 ENST00000491536.5  0     +
8    chr1                 11964701   11964702 ENST00000470133.1  0     +
9    chr1                 11971542   11971543 ENST00000481933.1  0     +
10   chr1                 22710838   22710839 ENST00000544305.5  0     +
11   chr1                 22710838   22710839 ENST00000374630.8  0     +
12   chr1                 22710964   22710965 ENST00000400191.7  0     +
13   chr1                 22710969   22710970 ENST00000374632.7  0     +
14   chr1                 22775177   22775178 ENST00000374627.1  0     +
15   chr1                 22800239   22800240 ENST00000465676.1  0     +
16   chr1                 22865158   22865159 ENST00000490436.1  0     +
17   chr1                 28369581   28369582 ENST00000633371.1  0     +
18   chr1                 28369608   28369609 ENST00000632202.1  0     +
19   chr1                 28369709   28369710 ENST00000632421.1  0     +
20   chr1                 28369738   28369739 ENST00000463428.5  0     +
21   chr1                 28369739   28369740 ENST00000373839.8  0     +
22   chr1                 28369743   28369744 ENST00000493669.2  0     +
23   chr1                 28438150   28438151 ENST00000633167.1  0     +
24   chr1                 28438170   28438171 ENST00000373836.4  0     +
25   chr1                 28491694   28491695 ENST00000632964.1  0     +
26   chr1                 37692480   37692481 ENST00000327331.2  0     +
27   chr1                 37692515   37692516 ENST00000373055.6  0     +
28   chr1                 43358980   43358981 ENST00000310955.11 0     +
29   chr1                 43359012   43359013 ENST00000372462.1  0     +
30   chr1                 43359766   43359767 ENST00000478882.1  0     +
⋮    ⋮                    ⋮          ⋮        ⋮                  ⋮     ⋮
2718 chr17_MU273379v1_fix 126299     126300   ENST00000707781.1  0     +
2719 chr17_MU273379v1_fix 126302     126303   ENST00000707782.1  0     +
2720 chr17_MU273379v1_fix 135707     135708   ENST00000707783.1  0     +
2721 chr17_MU273379v1_fix 136438     136439   ENST00000707784.1  0     +
2722 chr17_MU273379v1_fix 137089     137090   ENST00000707785.1  0     +
2723 chr17_MU273379v1_fix 141531     141532   ENST00000707786.1  0     +
2724 chr2_KQ983256v1_alt  388300     388301   ENST00000636761.3  0     +
2725 chr2_KQ983256v1_alt  388326     388327   ENST00000649768.1  0     +
2726 chr2_KQ983256v1_alt  388630     388631   ENST00000648555.1  0     +
2727 chr2_KQ983256v1_alt  388647     388648   ENST00000648142.1  0     +
2728 chr2_KQ983256v1_alt  388647     388648   ENST00000650133.1  0     +
2729 chr2_KQ983256v1_alt  388647     388648   ENST00000648655.1  0     +
2730 chr2_KQ983256v1_alt  388681     388682   ENST00000649010.1  0     +
2731 chr2_KQ983256v1_alt  389351     389352   ENST00000648496.1  0     +
2732 chr2_KQ983256v1_alt  393197     393198   ENST00000649836.1  0     +
2733 chr2_KQ983256v1_alt  405700     405701   ENST00000637549.1  0     +
2734 chrX_MU273395v1_alt  446156     446157   ENST00000709998.1  0     +
2735 chrX_MU273395v1_alt  446186     446187   ENST00000709999.1  0     +
2736 chrX_MU273395v1_alt  446252     446253   ENST00000710000.1  0     +
2737 chrX_MU273395v1_alt  513256     513257   ENST00000710010.1  0     +
2738 chrX_MU273395v1_alt  529631     529632   ENST00000710011.1  0     +
2739 chrX_MU273395v1_alt  529631     529632   ENST00000710012.1  0     +
2740 chrX_MU273395v1_alt  529642     529643   ENST00000710013.1  0     +
2741 chrX_MU273395v1_alt  529679     529680   ENST00000710014.1  0     +
2742 chrX_MU273395v1_alt  529679     529680   ENST00000710015.1  0     +
2743 chrX_MU273395v1_alt  529679     529680   ENST00000710016.1  0     +
2744 chrX_MU273395v1_alt  533054     533055   ENST00000710017.1  0     +
2745 chrX_MU273395v1_alt  535538     535539   ENST00000710018.1  0     +
2746 chrX_MU273395v1_alt  535896     535897   ENST00000710019.1  0     +
2747 chrX_MU273395v1_alt  556890     556891   ENST00000710020.1  0     +

##### now downregulated

In [25]:
mygenes <- read.delim("/usr/users/papantonis1/aman/rnaseq_data/mega_downregulated.tsv", header = FALSE)[[1]]

In [26]:
library(org.Hs.eg.db)

# Map gene symbols to Entrez IDs
mapped <- mapIds(org.Hs.eg.db,
                 keys = mygenes,
                 column = "ENTREZID",
                 keytype = "SYMBOL",
                 multiVals = "first")

# Remove NAs
entrez_ids <- na.omit(mapped)

'select()' returned 1:1 mapping between keys and columns

In [27]:
txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene
mygenes.transcripts <- subset(
  transcripts(txdb, columns = c("tx_id", "tx_name", "gene_id")),
  gene_id %in% entrez_ids
)

In [28]:
mygenes.tss <- resize(mygenes.transcripts, width=1, fix="start")

In [29]:
as.data.frame(mygenes.tss) # TSS position per transcript only

     seqnames             start   end     width strand tx_id
1    chr1                  960584  960584 1     +      130
2    chr1                  961449  961449 1     +      131
3    chr1                  962727  962727 1     +      132
4    chr1                  963552  963552 1     +      133
5    chr1                 1615454 1615454 1     +      245
6    chr1                 1615496 1615496 1     +      246
7    chr1                 1615500 1615500 1     +      247
8    chr1                 1615500 1615500 1     +      248
9    chr1                 1615500 1615500 1     +      249
10   chr1                 1615500 1615500 1     +      250
11   chr1                 1615514 1615514 1     +      251
12   chr1                 1615516 1615516 1     +      252
13   chr1                 1615530 1615530 1     +      253
14   chr1                 1615879 1615879 1     +      254
15   chr1                 1615887 1615887 1     +      255
16   chr1                 1615905 1615905 1     +      256
17   chr1                 1615914 1615914 1     +      257
18   chr1                 1615968 1615968 1     +      258
19   chr1                 1616274 1616274 1     +      259
20   chr1                 1616310 1616310 1     +      260
21   chr1                 1616311 1616311 1     +      261
22   chr1                 1617408 1617408 1     +      262
23   chr1                 1617560 1617560 1     +      263
24   chr1                 1617577 1617577 1     +      264
25   chr1                 1623122 1623122 1     +      265
26   chr1                 1623581 1623581 1     +      266
27   chr1                 1623802 1623802 1     +      267
28   chr1                 1624744 1624744 1     +      268
29   chr1                 1625087 1625087 1     +      269
30   chr1                 1625567 1625567 1     +      270
⋮    ⋮                    ⋮       ⋮       ⋮     ⋮      ⋮
1275 chr11_ML143358v1_fix  25307   25307  1     +      271884
1276 chr11_ML143358v1_fix  25374   25374  1     +      271885
1277 chr11_ML143358v1_fix  25609   25609  1     +      271886
1278 chr11_ML143358v1_fix  26063   26063  1     +      271887
1279 chr11_ML143358v1_fix  26532   26532  1     +      271888
1280 chr11_ML143358v1_fix  29484   29484  1     +      271889
1281 chr11_ML143358v1_fix  29984   29984  1     +      271890
1282 chr11_ML143358v1_fix  30176   30176  1     +      271891
1283 chr11_ML143358v1_fix  30200   30200  1     +      271892
1284 chr11_ML143358v1_fix  30697   30697  1     +      271893
1285 chr11_ML143358v1_fix  30721   30721  1     +      271894
1286 chr17_ML143374v1_fix  87681   87681  1     -      273978
1287 chr17_ML143374v1_fix  87700   87700  1     -      273979
1288 chr17_ML143374v1_fix  85865   85865  1     -      273980
1289 chr17_ML143374v1_fix  87758   87758  1     -      273981
1290 chr17_ML143374v1_fix  76273   76273  1     -      273982
1291 chr17_ML143374v1_fix  76978   76978  1     -      273983
1292 chr17_ML143374v1_fix  77106   77106  1     -      273984
1293 chr17_ML143374v1_fix  87631   87631  1     -      273985
1294 chr17_ML143374v1_fix  79174   79174  1     -      273986
1295 chr17_ML143374v1_fix  81329   81329  1     -      273987
1296 chr17_ML143374v1_fix  85204   85204  1     -      273988
1297 chr17_ML143374v1_fix  82735   82735  1     -      273989
1298 chr17_ML143374v1_fix  85202   85202  1     -      273990
1299 chr17_ML143374v1_fix  84889   84889  1     -      273991
1300 chr15_MU273375v1_alt 183550  183550  1     -      275858
1301 chr15_MU273375v1_alt 153782  153782  1     -      275859
1302 chr15_MU273375v1_alt 183900  183900  1     -      275860
1303 chr15_MU273375v1_alt 183558  183558  1     -      275862
1304 chr15_MU273375v1_alt 175017  175017  1     -      275863
     tx_name            gene_id
1    ENST00000338591.8  339451
2    ENST00000463212.1  339451
3    ENST00000466300.1  339451
4    ENST00000481067.1  339451
5    ENST00000479659.5  142678
6    ENST00000489635.5  142678
7    ENST00000355826.10 142678
8    ENST00000505820.7  142678
9    ENST00000518681.6  142678
10   ENST00000520777.6  142678
11   ENST00000511502.5  142678
12   ENST00000477990.1  142678
13   ENST00000514363.1  142678
14   ENST00000487053.5  142678
15   ENST00000502470.5  142678
16   ENST00000378712.5  142678
17   ENST00000507082.1  142678
18   ENST00000463492.1  142678
19   ENST00000510793.5  142678
20   ENST00000504599.6  142678
21   ENST00000507229.5  142678
22   ENST00000503789.5  142678
23   ENST00000378708.5  142678
24   ENST00000506488.5  142678
25   ENST00000512004.1  142678
26   ENST00000508455.1  142678
27   ENST00000514234.5  142678
28   ENST00000467597.1  142678
29   ENST00000508148.1  142678
30   ENST00000486072.1  142678
⋮    ⋮                  ⋮
1275 ENST00000673308.1  90019
1276 ENST00000673584.1  90019
1277 ENST00000672153.1  90019
1278 ENST00000673504.1  90019
1279 ENST00000672767.1  90019
1280 ENST00000673526.1   7136
1281 ENST00000672632.1   7136
1282 ENST00000673373.1   7136
1283 ENST00000672014.1   7136
1284 ENST00000672155.1   7136
1285 ENST00000672424.1   7136
1286 ENST00000673081.1  84461
1287 ENST00000671847.1  84461
1288 ENST00000672688.1  84461
1289 ENST00000672757.1  84461
1290 ENST00000672144.1  84461
1291 ENST00000672456.1  84461
1292 ENST00000672687.1  84461
1293 ENST00000673278.1  84461
1294 ENST00000672398.1  84461
1295 ENST00000673575.1  84461
1296 ENST00000672813.1  84461
1297 ENST00000673148.1  84461
1298 ENST00000672441.1  84461
1299 ENST00000672181.1  84461
1300 ENST00000709510.1  23015
1301 ENST00000709511.1  23015
1302 ENST00000709512.1  23015
1303 ENST00000709513.1  23015
1304 ENST00000709514.1  23015

In [30]:
# Converting to dataframe
tss_df <- as.data.frame(mygenes.tss)

# Creating a .bed like table
bed_tss_df <- data.frame(
  chrom = tss_df$seqnames,
  chromStart = tss_df$start - 1,  # BED is 0-based
  chromEnd = tss_df$start,        # 1 bp region
  name = tss_df$tx_name,          
  score = 0,                      # just a standard
  strand = tss_df$strand
)

# Export to BED
write.table(bed_tss_df, file = "downregulated_transcript_level_TSS.bed",
            sep = "\t", quote = FALSE, row.names = FALSE, col.names = FALSE)

In [31]:
tss_df

     seqnames             start   end     width strand tx_id
1    chr1                  960584  960584 1     +      130
2    chr1                  961449  961449 1     +      131
3    chr1                  962727  962727 1     +      132
4    chr1                  963552  963552 1     +      133
5    chr1                 1615454 1615454 1     +      245
6    chr1                 1615496 1615496 1     +      246
7    chr1                 1615500 1615500 1     +      247
8    chr1                 1615500 1615500 1     +      248
9    chr1                 1615500 1615500 1     +      249
10   chr1                 1615500 1615500 1     +      250
11   chr1                 1615514 1615514 1     +      251
12   chr1                 1615516 1615516 1     +      252
13   chr1                 1615530 1615530 1     +      253
14   chr1                 1615879 1615879 1     +      254
15   chr1                 1615887 1615887 1     +      255
16   chr1                 1615905 1615905 1     +      256
17   chr1                 1615914 1615914 1     +      257
18   chr1                 1615968 1615968 1     +      258
19   chr1                 1616274 1616274 1     +      259
20   chr1                 1616310 1616310 1     +      260
21   chr1                 1616311 1616311 1     +      261
22   chr1                 1617408 1617408 1     +      262
23   chr1                 1617560 1617560 1     +      263
24   chr1                 1617577 1617577 1     +      264
25   chr1                 1623122 1623122 1     +      265
26   chr1                 1623581 1623581 1     +      266
27   chr1                 1623802 1623802 1     +      267
28   chr1                 1624744 1624744 1     +      268
29   chr1                 1625087 1625087 1     +      269
30   chr1                 1625567 1625567 1     +      270
⋮    ⋮                    ⋮       ⋮       ⋮     ⋮      ⋮
1275 chr11_ML143358v1_fix  25307   25307  1     +      271884
1276 chr11_ML143358v1_fix  25374   25374  1     +      271885
1277 chr11_ML143358v1_fix  25609   25609  1     +      271886
1278 chr11_ML143358v1_fix  26063   26063  1     +      271887
1279 chr11_ML143358v1_fix  26532   26532  1     +      271888
1280 chr11_ML143358v1_fix  29484   29484  1     +      271889
1281 chr11_ML143358v1_fix  29984   29984  1     +      271890
1282 chr11_ML143358v1_fix  30176   30176  1     +      271891
1283 chr11_ML143358v1_fix  30200   30200  1     +      271892
1284 chr11_ML143358v1_fix  30697   30697  1     +      271893
1285 chr11_ML143358v1_fix  30721   30721  1     +      271894
1286 chr17_ML143374v1_fix  87681   87681  1     -      273978
1287 chr17_ML143374v1_fix  87700   87700  1     -      273979
1288 chr17_ML143374v1_fix  85865   85865  1     -      273980
1289 chr17_ML143374v1_fix  87758   87758  1     -      273981
1290 chr17_ML143374v1_fix  76273   76273  1     -      273982
1291 chr17_ML143374v1_fix  76978   76978  1     -      273983
1292 chr17_ML143374v1_fix  77106   77106  1     -      273984
1293 chr17_ML143374v1_fix  87631   87631  1     -      273985
1294 chr17_ML143374v1_fix  79174   79174  1     -      273986
1295 chr17_ML143374v1_fix  81329   81329  1     -      273987
1296 chr17_ML143374v1_fix  85204   85204  1     -      273988
1297 chr17_ML143374v1_fix  82735   82735  1     -      273989
1298 chr17_ML143374v1_fix  85202   85202  1     -      273990
1299 chr17_ML143374v1_fix  84889   84889  1     -      273991
1300 chr15_MU273375v1_alt 183550  183550  1     -      275858
1301 chr15_MU273375v1_alt 153782  153782  1     -      275859
1302 chr15_MU273375v1_alt 183900  183900  1     -      275860
1303 chr15_MU273375v1_alt 183558  183558  1     -      275862
1304 chr15_MU273375v1_alt 175017  175017  1     -      275863
     tx_name            gene_id
1    ENST00000338591.8  339451
2    ENST00000463212.1  339451
3    ENST00000466300.1  339451
4    ENST00000481067.1  339451
5    ENST00000479659.5  142678
6    ENST00000489635.5  142678
7    ENST00000355826.10 142678
8    ENST00000505820.7  142678
9    ENST00000518681.6  142678
10   ENST00000520777.6  142678
11   ENST00000511502.5  142678
12   ENST00000477990.1  142678
13   ENST00000514363.1  142678
14   ENST00000487053.5  142678
15   ENST00000502470.5  142678
16   ENST00000378712.5  142678
17   ENST00000507082.1  142678
18   ENST00000463492.1  142678
19   ENST00000510793.5  142678
20   ENST00000504599.6  142678
21   ENST00000507229.5  142678
22   ENST00000503789.5  142678
23   ENST00000378708.5  142678
24   ENST00000506488.5  142678
25   ENST00000512004.1  142678
26   ENST00000508455.1  142678
27   ENST00000514234.5  142678
28   ENST00000467597.1  142678
29   ENST00000508148.1  142678
30   ENST00000486072.1  142678
⋮    ⋮                  ⋮
1275 ENST00000673308.1  90019
1276 ENST00000673584.1  90019
1277 ENST00000672153.1  90019
1278 ENST00000673504.1  90019
1279 ENST00000672767.1  90019
1280 ENST00000673526.1   7136
1281 ENST00000672632.1   7136
1282 ENST00000673373.1   7136
1283 ENST00000672014.1   7136
1284 ENST00000672155.1   7136
1285 ENST00000672424.1   7136
1286 ENST00000673081.1  84461
1287 ENST00000671847.1  84461
1288 ENST00000672688.1  84461
1289 ENST00000672757.1  84461
1290 ENST00000672144.1  84461
1291 ENST00000672456.1  84461
1292 ENST00000672687.1  84461
1293 ENST00000673278.1  84461
1294 ENST00000672398.1  84461
1295 ENST00000673575.1  84461
1296 ENST00000672813.1  84461
1297 ENST00000673148.1  84461
1298 ENST00000672441.1  84461
1299 ENST00000672181.1  84461
1300 ENST00000709510.1  23015
1301 ENST00000709511.1  23015
1302 ENST00000709512.1  23015
1303 ENST00000709513.1  23015
1304 ENST00000709514.1  23015

In [32]:
bed_tss_df

     chrom                chromStart chromEnd name               score strand
1    chr1                  960583     960584  ENST00000338591.8  0     +
2    chr1                  961448     961449  ENST00000463212.1  0     +
3    chr1                  962726     962727  ENST00000466300.1  0     +
4    chr1                  963551     963552  ENST00000481067.1  0     +
5    chr1                 1615453    1615454  ENST00000479659.5  0     +
6    chr1                 1615495    1615496  ENST00000489635.5  0     +
7    chr1                 1615499    1615500  ENST00000355826.10 0     +
8    chr1                 1615499    1615500  ENST00000505820.7  0     +
9    chr1                 1615499    1615500  ENST00000518681.6  0     +
10   chr1                 1615499    1615500  ENST00000520777.6  0     +
11   chr1                 1615513    1615514  ENST00000511502.5  0     +
12   chr1                 1615515    1615516  ENST00000477990.1  0     +
13   chr1                 1615529    1615530  ENST00000514363.1  0     +
14   chr1                 1615878    1615879  ENST00000487053.5  0     +
15   chr1                 1615886    1615887  ENST00000502470.5  0     +
16   chr1                 1615904    1615905  ENST00000378712.5  0     +
17   chr1                 1615913    1615914  ENST00000507082.1  0     +
18   chr1                 1615967    1615968  ENST00000463492.1  0     +
19   chr1                 1616273    1616274  ENST00000510793.5  0     +
20   chr1                 1616309    1616310  ENST00000504599.6  0     +
21   chr1                 1616310    1616311  ENST00000507229.5  0     +
22   chr1                 1617407    1617408  ENST00000503789.5  0     +
23   chr1                 1617559    1617560  ENST00000378708.5  0     +
24   chr1                 1617576    1617577  ENST00000506488.5  0     +
25   chr1                 1623121    1623122  ENST00000512004.1  0     +
26   chr1                 1623580    1623581  ENST00000508455.1  0     +
27   chr1                 1623801    1623802  ENST00000514234.5  0     +
28   chr1                 1624743    1624744  ENST00000467597.1  0     +
29   chr1                 1625086    1625087  ENST00000508148.1  0     +
30   chr1                 1625566    1625567  ENST00000486072.1  0     +
⋮    ⋮                    ⋮          ⋮        ⋮                  ⋮     ⋮
1275 chr11_ML143358v1_fix  25306      25307   ENST00000673308.1  0     +
1276 chr11_ML143358v1_fix  25373      25374   ENST00000673584.1  0     +
1277 chr11_ML143358v1_fix  25608      25609   ENST00000672153.1  0     +
1278 chr11_ML143358v1_fix  26062      26063   ENST00000673504.1  0     +
1279 chr11_ML143358v1_fix  26531      26532   ENST00000672767.1  0     +
1280 chr11_ML143358v1_fix  29483      29484   ENST00000673526.1  0     +
1281 chr11_ML143358v1_fix  29983      29984   ENST00000672632.1  0     +
1282 chr11_ML143358v1_fix  30175      30176   ENST00000673373.1  0     +
1283 chr11_ML143358v1_fix  30199      30200   ENST00000672014.1  0     +
1284 chr11_ML143358v1_fix  30696      30697   ENST00000672155.1  0     +
1285 chr11_ML143358v1_fix  30720      30721   ENST00000672424.1  0     +
1286 chr17_ML143374v1_fix  87680      87681   ENST00000673081.1  0     -
1287 chr17_ML143374v1_fix  87699      87700   ENST00000671847.1  0     -
1288 chr17_ML143374v1_fix  85864      85865   ENST00000672688.1  0     -
1289 chr17_ML143374v1_fix  87757      87758   ENST00000672757.1  0     -
1290 chr17_ML143374v1_fix  76272      76273   ENST00000672144.1  0     -
1291 chr17_ML143374v1_fix  76977      76978   ENST00000672456.1  0     -
1292 chr17_ML143374v1_fix  77105      77106   ENST00000672687.1  0     -
1293 chr17_ML143374v1_fix  87630      87631   ENST00000673278.1  0     -
1294 chr17_ML143374v1_fix  79173      79174   ENST00000672398.1  0     -
1295 chr17_ML143374v1_fix  81328      81329   ENST00000673575.1  0     -
1296 chr17_ML143374v1_fix  85203      85204   ENST00000672813.1  0     -
1297 chr17_ML143374v1_fix  82734      82735   ENST00000673148.1  0     -
1298 chr17_ML143374v1_fix  85201      85202   ENST00000672441.1  0     -
1299 chr17_ML143374v1_fix  84888      84889   ENST00000672181.1  0     -
1300 chr15_MU273375v1_alt 183549     183550   ENST00000709510.1  0     -
1301 chr15_MU273375v1_alt 153781     153782   ENST00000709511.1  0     -
1302 chr15_MU273375v1_alt 183899     183900   ENST00000709512.1  0     -
1303 chr15_MU273375v1_alt 183557     183558   ENST00000709513.1  0     -
1304 chr15_MU273375v1_alt 175016     175017   ENST00000709514.1  0     -