In [1]:
import deeptools as dt
import pandas as pd

In [2]:
# func

def split_and_exp(csv):
    bedpe = pd.read_csv(csv, sep="\t", header=None)
    left_anchors = bedpe.iloc[:, [0, 1, 2]].set_axis([0, 1, 2], axis=1)
    left_anchors["anchor"] = "left"
    right_anchors = bedpe.iloc[:, [3, 4, 5]].set_axis([0, 1, 2], axis=1)
    right_anchors["anchor"] = "right"
    all_anchors_all = pd.concat([left_anchors, right_anchors], ignore_index=True)
    return all_anchors_all

In [3]:
# ctcf

In [4]:
# first split bedpe to left and right anchors and then concatenate them into a single bed file
ctcf_bedpe = pd.read_csv("/usr/users/papantonis1/aman/microc_project/loop_calling_premade_hic/merged_loops_3tools/ctcf_associated_loops_eitheranchoroverlap_ctrl.bedpe", sep="\t", header=None)
ctcf_bedpe

         0          1          2     3          4          5
0     chr1    8022500    8027500  chr1    8312500    8317500
1     chr1    8025000    8030000  chr1    8090000    8095000
2     chr1    8025000    8030000  chr1    8170000    8175000
3     chr1    8025000    8030000  chr1    8240000    8245000
4     chr1    8095000    8100000  chr1    8310000    8315000
...    ...        ...        ...   ...        ...        ...
3355  chr9  114805000  114810000  chr9  114905000  114910000
3356  chr9  129882500  129887500  chr9  130102500  130107500
3357  chr9  135082500  135087500  chr9  135342500  135347500
3358  chrX   68822500   68827500  chrX   69382500   69387500
3359  chrX   70192500   70197500  chrX   70432500   70437500

[3360 rows x 6 columns]

In [5]:
#extracting cols
left_anchors = ctcf_bedpe.iloc[:, [0, 1, 2]].set_axis([0, 1, 2], axis=1)
left_anchors["anchor"] = "left"
#left_anchors
right_anchors = ctcf_bedpe.iloc[:, [3, 4, 5]].set_axis([0, 1, 2], axis=1)
right_anchors["anchor"] = "right"
right_anchors

         0          1          2 anchor
0     chr1    8312500    8317500  right
1     chr1    8090000    8095000  right
2     chr1    8170000    8175000  right
3     chr1    8240000    8245000  right
4     chr1    8310000    8315000  right
...    ...        ...        ...    ...
3355  chr9  114905000  114910000  right
3356  chr9  130102500  130107500  right
3357  chr9  135342500  135347500  right
3358  chrX   69382500   69387500  right
3359  chrX   70432500   70437500  right

[3360 rows x 4 columns]

In [6]:
#concat
all_anchors = pd.concat([left_anchors, right_anchors], ignore_index=True)
all_anchors

         0          1          2 anchor
0     chr1    8022500    8027500   left
1     chr1    8025000    8030000   left
2     chr1    8025000    8030000   left
3     chr1    8025000    8030000   left
4     chr1    8095000    8100000   left
...    ...        ...        ...    ...
6715  chr9  114905000  114910000  right
6716  chr9  130102500  130107500  right
6717  chr9  135342500  135347500  right
6718  chrX   69382500   69387500  right
6719  chrX   70432500   70437500  right

[6720 rows x 4 columns]

In [7]:
all_anchors.to_csv("ctrl_ctcf_anchors_eitheranchoroverlap_derived.csv", sep="\t",header=False,index=False)

In [8]:
ctcf_rbp1 = split_and_exp("/usr/users/papantonis1/aman/microc_project/loop_calling_premade_hic/merged_loops_3tools/ctcf_associated_loops_eitheranchoroverlap_rbp1.bedpe")
ctcf_rbp1.to_csv("rbp1_ctcf_anchors_eitheranchoroverlap_derived.csv", sep="\t",header=False,index=False)

In [9]:
# h3k27me3

In [10]:
#ctrl
h3k27_ctrl = split_and_exp("/usr/users/papantonis1/aman/microc_project/loop_calling_premade_hic/merged_loops_3tools/h3k27me3_associated_loops_eitheranchoroverlap_ctrl.bedpe")

In [11]:
h3k27_ctrl.to_csv("ctrl_h3k27_anchors_eitheranchoroverlap_derived.csv", sep="\t",header=False,index=False)

In [12]:
#rbp1
h3k27_rbp1 = split_and_exp("/usr/users/papantonis1/aman/microc_project/loop_calling_premade_hic/merged_loops_3tools/h3k27me3_associated_loops_eitheranchoroverlap_rbp1.bedpe")
h3k27_rbp1.to_csv("rbp1_h3k27_anchors_eitheranchoroverlap_derived.csv", sep="\t",header=False,index=False)

In [14]:
## using subprocess
import subprocess

result = subprocess.run([
    "computeMatrix", "reference-point",
    "--referencePoint", "center",
    "-b", "2500", "-a", "2500",
    "-R",
    "/usr/users/papantonis1/aman/microc_project/loop_calling_premade_hic/jupyter_notes/ctrl_ctcf_anchors_eitheranchoroverlap_derived.csv",
    "/usr/users/papantonis1/aman/microc_project/loop_calling_premade_hic/jupyter_notes/ctrl_h3k27_anchors_eitheranchoroverlap_derived.csv",
    "-S",
    "/usr/users/papantonis1/aman/microc_data/nadine_macro/C_CTCF.bw_RPGC.bw",
    "/usr/users/papantonis1/aman/microc_data/cut_n_tag/nadine_cut_tag/nadine_cut_tag/C_H3K27me3_results/Aligned_files/Bigwig_scaled/C_H3K27me3.bw_RPGC.bw",
    "--skipZeros",
    "--missingDataAsZero",
    "-out", "chromatin_signal_matrix.gz",
    "--outFileSortedRegions", "anchors_sorted.bed"
],
capture_output=True,
text=True
)

print(result.stdout)

print("STDERR:")
print(result.stderr)

# Optional: check if it failed
if result.returncode != 0:
    print("Error: computeMatrix failed")

STDERR:
Skipping chr10:20852500-20857500, due to being absent in the computeMatrix output.
Skipping chr10:32262500-32267500, due to being absent in the computeMatrix output.
Skipping chr10:69005000-69010000, due to being absent in the computeMatrix output.
Skipping chr10:113132500-113137500, due to being absent in the computeMatrix output.
Skipping chr11:10202500-10207500, due to being absent in the computeMatrix output.
Skipping chr12:62802500-62807500, due to being absent in the computeMatrix output.
Skipping chr13:80032500-80037500, due to being absent in the computeMatrix output.
Skipping chr16:55555000-55560000, due to being absent in the computeMatrix output.
Skipping chr17:15840000-15845000, due to being absent in the computeMatrix output.
Skipping chr2:47852500-47857500, due to being absent in the computeMatrix output.
Skipping chr21:27710000-27715000, due to being absent in the computeMatrix output.
Skipping chr3:45095000-45100000, due to being absent in the computeMatrix output.
Skipping chr3:150360000-150365000, due to being absent in the computeMatrix output.
Skipping chr4:139170000-139175000, due to being absent in the computeMatrix output.
Skipping chr4:142735000-142740000, due to being absent in the computeMatrix output.
Skipping chr6:125782500-125787500, due to being absent in the computeMatrix output.
Skipping chr7:38122500-38127500, due to being absent in the computeMatrix output.
Skipping chr7:54850000-54855000, due to being absent in the computeMatrix output.
Skipping chr9:132660000-132665000, due to being absent in the computeMatrix output.
Skipping chrX:7075000-7080000, due to being absent in the computeMatrix output.
Skipping chr10:80385000-80390000, due to being absent in the computeMatrix output.
Skipping chr10:84362500-84367500, due to being absent in the computeMatrix output.
Skipping chr11:12312500-12317500, due to being absent in the computeMatrix output.
Skipping chr13:29772500-29777500, due to being absent in the computeMatrix output.
Skipping chr14:35142500-35147500, due to being absent in the computeMatrix output.
Skipping chr15:84850000-84855000, due to being absent in the computeMatrix output.
Skipping chr2:47900000-47905000, due to being absent in the computeMatrix output.
Skipping chr2:60085000-60090000, due to being absent in the computeMatrix output.
Skipping chr20:4002500-4007500, due to being absent in the computeMatrix output.
Skipping chr22:30112500-30117500, due to being absent in the computeMatrix output.
Skipping chr7:128612500-128617500, due to being absent in the computeMatrix output.
Skipping chr7:151562500-151567500, due to being absent in the computeMatrix output.
Skipping chr8:30192500-30197500, due to being absent in the computeMatrix output.
Skipping chr1:178742500-178747500, due to being absent in the computeMatrix output.
Skipping chr10:73062500-73067500, due to being absent in the computeMatrix output.
Skipping chr10:84362500-84367500_r1, due to being absent in the computeMatrix output.
Skipping chr10:95832500-95837500, due to being absent in the computeMatrix output.
Skipping chr11:11012500-11017500, due to being absent in the computeMatrix output.
Skipping chr11:69505000-69510000, due to being absent in the computeMatrix output.
Skipping chr12:42572500-42577500, due to being absent in the computeMatrix output.
Skipping chr14:49832500-49837500, due to being absent in the computeMatrix output.
Skipping chr14:77552500-77557500, due to being absent in the computeMatrix output.
Skipping chr17:65382500-65387500, due to being absent in the computeMatrix output.
Skipping chr18:13152500-13157500, due to being absent in the computeMatrix output.
Skipping chr19:52240000-52245000, due to being absent in the computeMatrix output.
Skipping chr2:63032500-63037500, due to being absent in the computeMatrix output.
Skipping chr2:72572500-72577500, due to being absent in the computeMatrix output.
Skipping chr22:35925000-35930000, due to being absent in the computeMatrix output.
Skipping chr3:134292500-134297500, due to being absent in the computeMatrix output.
Skipping chr3:185482500-185487500, due to being absent in the computeMatrix output.
Skipping chr5:142552500-142557500, due to being absent in the computeMatrix output.
Skipping chr6:106810000-106815000, due to being absent in the computeMatrix output.
Skipping chr6:147972500-147977500, due to being absent in the computeMatrix output.
Skipping chr6:158962500-158967500, due to being absent in the computeMatrix output.
Skipping chr7:20202500-20207500, due to being absent in the computeMatrix output.
Skipping chr7:23425000-23430000, due to being absent in the computeMatrix output.
Skipping chr7:37105000-37110000, due to being absent in the computeMatrix output.
Skipping chr9:4735000-4740000, due to being absent in the computeMatrix output.
Skipping chr9:90652500-90657500, due to being absent in the computeMatrix output.
Skipping chr9:92300000-92305000, due to being absent in the computeMatrix output.
Skipping chr1:223912500-223917500, due to being absent in the computeMatrix output.
Skipping chr10:46582500-46587500, due to being absent in the computeMatrix output.
Skipping chr10:114442500-114447500, due to being absent in the computeMatrix output.
Skipping chr13:33532500-33537500, due to being absent in the computeMatrix output.
Skipping chr15:82992500-82997500, due to being absent in the computeMatrix output.
Skipping chr17:65405000-65410000, due to being absent in the computeMatrix output.
Skipping chr20:51602500-51607500, due to being absent in the computeMatrix output.
Skipping chr5:68242500-68247500, due to being absent in the computeMatrix output.
Skipping chr10:49522500-49527500, due to being absent in the computeMatrix output.
Skipping chr11:59682500-59687500, due to being absent in the computeMatrix output.
Skipping chr14:92770000-92775000, due to being absent in the computeMatrix output.
Skipping chr3:188482500-188487500, due to being absent in the computeMatrix output.
Skipping chr4:186805000-186810000, due to being absent in the computeMatrix output.
Skipping chr1:100915000-100920000, due to being absent in the computeMatrix output.
Skipping chr3:67372500-67377500, due to being absent in the computeMatrix output.
Skipping chr5:177892500-177897500, due to being absent in the computeMatrix output.
Skipping chr8:35152500-35157500, due to being absent in the computeMatrix output.
Skipping chr11:130752500-130757500, due to being absent in the computeMatrix output.
Skipping chr10:52490000-52495000, due to being absent in the computeMatrix output.
Skipping chr15:60450000-60455000, due to being absent in the computeMatrix output.
Skipping chr5:146122500-146127500, due to being absent in the computeMatrix output.
Skipping chr9:37282500-37287500, due to being absent in the computeMatrix output.
Skipping chr2:60992500-60997500, due to being absent in the computeMatrix output.
Skipping chr3:134292500-134297500, due to being absent in the computeMatrix output.

In [2]:
import subprocess

subprocess.run([
    "plotHeatmap",
    "-m", "chromatin_signal_matrix.gz",
    "-out", "chromatin_signal_heatmap_labeled.png",
    "--colorMap", "RdBu_r",
    "--whatToShow", "heatmap and colorbar",
    "--zMin", "0",
    "--zMax", "200",
    "--refPointLabel", "Anchor center",
    "--regionsLabel", "CTCF_anchors", "H3K27me3_anchors",
    "--samplesLabel", "CTCF_signal", "H3K27me3_signal",
    "--plotTitle", "CUT&TAG Signal Heatmap"
])

CompletedProcess(args=['plotHeatmap', '-m', 'chromatin_signal_matrix.gz', '-out', 'chromatin_signal_heatmap_labeled.png', '--colorMap', 'RdBu_r', '--whatToShow', 'heatmap and colorbar', '--zMin', '0', '--zMax', '200', '--refPointLabel', 'Anchor center', '--regionsLabel', 'CTCF_anchors', 'H3K27me3_anchors', '--samplesLabel', 'CTCF_signal', 'H3K27me3_signal', '--plotTitle', 'CUT&TAG Signal Heatmap'], returncode=0)

---

In [16]:
# doing it individually 
# h3k27me3

## using subprocess
import subprocess

result = subprocess.run([
    "computeMatrix", "reference-point",
    "--referencePoint", "center",
    "-b", "2500", "-a", "2500",
    "-R",
    "/usr/users/papantonis1/aman/microc_project/loop_calling_premade_hic/jupyter_notes/ctrl_h3k27_anchors_eitheranchoroverlap_derived.csv",
    "-S",
    "/usr/users/papantonis1/aman/microc_data/cut_n_tag/nadine_cut_tag/nadine_cut_tag/C_H3K27me3_results/Aligned_files/Bigwig_scaled/C_H3K27me3.bw_RPGC.bw",
    "--skipZeros",
    "--missingDataAsZero",
    "-out", "ctrl_h3k27_chromatin_signal_matrix.gz",
    "--outFileSortedRegions", "ctrl_h3k27_anchors_sorted.bed"
],
capture_output=True,
text=True
)

print(result.stdout)

print("STDERR:")
print(result.stderr)

# Optional: check if it failed
if result.returncode != 0:
    print("Error: computeMatrix failed")

STDERR:
Skipping chr1:100922500-100927500, due to being absent in the computeMatrix output.
Skipping chr10:101055000-101060000, due to being absent in the computeMatrix output.
Skipping chr10:119750000-119755000, due to being absent in the computeMatrix output.
Skipping chr11:20392500-20397500, due to being absent in the computeMatrix output.
Skipping chr11:82905000-82910000, due to being absent in the computeMatrix output.
Skipping chr11:113805000-113810000, due to being absent in the computeMatrix output.
Skipping chr12:66142500-66147500, due to being absent in the computeMatrix output.
Skipping chr14:61450000-61455000, due to being absent in the computeMatrix output.
Skipping chr14:74102500-74107500, due to being absent in the computeMatrix output.
Skipping chr14:99502500-99507500, due to being absent in the computeMatrix output.
Skipping chr16:71225000-71230000, due to being absent in the computeMatrix output.
Skipping chr17:47672500-47677500, due to being absent in the computeMatrix output.
Skipping chr18:13002500-13007500, due to being absent in the computeMatrix output.
Skipping chr19:49220000-49225000, due to being absent in the computeMatrix output.
Skipping chr2:97812500-97817500, due to being absent in the computeMatrix output.
Skipping chr2:164730000-164735000, due to being absent in the computeMatrix output.
Skipping chr22:26500000-26505000, due to being absent in the computeMatrix output.
Skipping chr3:122392500-122397500, due to being absent in the computeMatrix output.
Skipping chr4:4482500-4487500, due to being absent in the computeMatrix output.
Skipping chr6:44102500-44107500, due to being absent in the computeMatrix output.
Skipping chr7:130072500-130077500, due to being absent in the computeMatrix output.
Skipping chr9:86462500-86467500, due to being absent in the computeMatrix output.
Skipping chr9:86482500-86487500, due to being absent in the computeMatrix output.
Skipping chr1:100915000-100920000, due to being absent in the computeMatrix output.
Skipping chr1:197610000-197615000, due to being absent in the computeMatrix output.
Skipping chr17:10770000-10775000, due to being absent in the computeMatrix output.
Skipping chr18:76872500-76877500, due to being absent in the computeMatrix output.
Skipping chr2:235782500-235787500, due to being absent in the computeMatrix output.
Skipping chr3:38512500-38517500, due to being absent in the computeMatrix output.
Skipping chr3:67372500-67377500, due to being absent in the computeMatrix output.
Skipping chr4:4482500-4487500_r1, due to being absent in the computeMatrix output.
Skipping chr5:177892500-177897500, due to being absent in the computeMatrix output.
Skipping chr8:35152500-35157500, due to being absent in the computeMatrix output.
Skipping chr11:130752500-130757500, due to being absent in the computeMatrix output.
Skipping chr10:52490000-52495000, due to being absent in the computeMatrix output.
Skipping chr11:76320000-76325000, due to being absent in the computeMatrix output.
Skipping chr15:60450000-60455000, due to being absent in the computeMatrix output.
Skipping chr19:41800000-41805000, due to being absent in the computeMatrix output.
Skipping chr19:51095000-51100000, due to being absent in the computeMatrix output.
Skipping chr2:199360000-199365000, due to being absent in the computeMatrix output.
Skipping chr4:120052500-120057500, due to being absent in the computeMatrix output.
Skipping chr7:45850000-45855000, due to being absent in the computeMatrix output.
Skipping chr8:41970000-41975000, due to being absent in the computeMatrix output.
Skipping chr8:140392500-140397500, due to being absent in the computeMatrix output.
Skipping chr9:132905000-132910000, due to being absent in the computeMatrix output.
Skipping chr10:46022500-46027500, due to being absent in the computeMatrix output.
Skipping chr11:17972500-17977500, due to being absent in the computeMatrix output.
Skipping chr11:66832500-66837500, due to being absent in the computeMatrix output.
Skipping chr17:8180000-8185000, due to being absent in the computeMatrix output.
Skipping chr3:123552500-123557500, due to being absent in the computeMatrix output.
Skipping chr5:146122500-146127500, due to being absent in the computeMatrix output.
Skipping chr7:775000-780000, due to being absent in the computeMatrix output.
Skipping chr9:37282500-37287500, due to being absent in the computeMatrix output.
Skipping chr10:66182500-66187500, due to being absent in the computeMatrix output.
Skipping chr2:60992500-60997500, due to being absent in the computeMatrix output.
Skipping chr3:134292500-134297500, due to being absent in the computeMatrix output.
Skipping chr7:90422500-90427500, due to being absent in the computeMatrix output.

In [20]:
import subprocess

subprocess.run([
    "plotHeatmap",
    "-m", "ctrl_h3k27_chromatin_signal_matrix.gz",
    "-out", "ctrl_h3k27_chromatin_signal_heatmap_labeled.png",
    "--colorMap", "RdBu_r",
    "--whatToShow", "heatmap and colorbar",
    "--zMin", "0",
    "--zMax", "200",
    "--refPointLabel", "Anchor center",
    "--regionsLabel", "H3K27me3_anchors",
    "--samplesLabel", "H3K27me3_signal",
    "--plotTitle", "CUT&TAG Signal Heatmap"
])

CompletedProcess(args=['plotHeatmap', '-m', 'ctrl_h3k27_chromatin_signal_matrix.gz', '-out', 'ctrl_h3k27_chromatin_signal_heatmap_labeled.png', '--colorMap', 'RdBu_r', '--whatToShow', 'heatmap and colorbar', '--zMin', '0', '--zMax', '200', '--refPointLabel', 'Anchor center', '--regionsLabel', 'H3K27me3_anchors', '--samplesLabel', 'H3K27me3_signal', '--plotTitle', 'CUT&TAG Signal Heatmap'], returncode=0)

---

In [18]:
# doing it individually 
# ctcf

## using subprocess
import subprocess

result = subprocess.run([
    "computeMatrix", "reference-point",
    "--referencePoint", "center",
    "-b", "2500", "-a", "2500",
    "-R",
    "/usr/users/papantonis1/aman/microc_project/loop_calling_premade_hic/jupyter_notes/ctrl_ctcf_anchors_eitheranchoroverlap_derived.csv",
    "-S",
    "/usr/users/papantonis1/aman/microc_data/nadine_macro/C_CTCF.bw_RPGC.bw",
    "--skipZeros",
    "--missingDataAsZero",
    "-out", "ctrl_ctcf_chromatin_signal_matrix.gz",
    "--outFileSortedRegions", "ctrl_ctcf_anchors_sorted.bed"
],
capture_output=True,
text=True
)

print(result.stdout)

print("STDERR:")
print(result.stderr)

# Optional: check if it failed
if result.returncode != 0:
    print("Error: computeMatrix failed")

STDERR:
Skipping chr1:13972500-13977500, due to being absent in the computeMatrix output.
Skipping chr1:33210000-33215000, due to being absent in the computeMatrix output.
Skipping chr1:44382500-44387500, due to being absent in the computeMatrix output.
Skipping chr1:49202500-49207500, due to being absent in the computeMatrix output.
Skipping chr1:53985000-53990000, due to being absent in the computeMatrix output.
Skipping chr1:83912500-83917500, due to being absent in the computeMatrix output.
Skipping chr1:84132500-84137500, due to being absent in the computeMatrix output.
Skipping chr1:172432500-172437500, due to being absent in the computeMatrix output.
Skipping chr1:183642500-183647500, due to being absent in the computeMatrix output.
Skipping chr1:220202500-220207500, due to being absent in the computeMatrix output.
Skipping chr1:225550000-225555000, due to being absent in the computeMatrix output.
Skipping chr10:20852500-20857500, due to being absent in the computeMatrix output.
Skipping chr10:32262500-32267500, due to being absent in the computeMatrix output.
Skipping chr10:69005000-69010000, due to being absent in the computeMatrix output.
Skipping chr10:86392500-86397500, due to being absent in the computeMatrix output.
Skipping chr10:113132500-113137500, due to being absent in the computeMatrix output.
Skipping chr11:10202500-10207500, due to being absent in the computeMatrix output.
Skipping chr11:14782500-14787500, due to being absent in the computeMatrix output.
Skipping chr11:64390000-64395000, due to being absent in the computeMatrix output.
Skipping chr11:72920000-72925000, due to being absent in the computeMatrix output.
Skipping chr11:122025000-122030000, due to being absent in the computeMatrix output.
Skipping chr12:62802500-62807500, due to being absent in the computeMatrix output.
Skipping chr12:77712500-77717500, due to being absent in the computeMatrix output.
Skipping chr12:113452500-113457500, due to being absent in the computeMatrix output.
Skipping chr13:24595000-24600000, due to being absent in the computeMatrix output.
Skipping chr13:29842500-29847500, due to being absent in the computeMatrix output.
Skipping chr13:80032500-80037500, due to being absent in the computeMatrix output.
Skipping chr13:96022500-96027500, due to being absent in the computeMatrix output.
Skipping chr13:105132500-105137500, due to being absent in the computeMatrix output.
Skipping chr14:20320000-20325000, due to being absent in the computeMatrix output.
Skipping chr14:20615000-20620000, due to being absent in the computeMatrix output.
Skipping chr14:35232500-35237500, due to being absent in the computeMatrix output.
Skipping chr14:73900000-73905000, due to being absent in the computeMatrix output.
Skipping chr14:94425000-94430000, due to being absent in the computeMatrix output.
Skipping chr15:31005000-31010000, due to being absent in the computeMatrix output.
Skipping chr15:70755000-70760000, due to being absent in the computeMatrix output.
Skipping chr16:20842500-20847500, due to being absent in the computeMatrix output.
Skipping chr16:55555000-55560000, due to being absent in the computeMatrix output.
Skipping chr16:58175000-58180000, due to being absent in the computeMatrix output.
Skipping chr17:12182500-12187500, due to being absent in the computeMatrix output.
Skipping chr17:15840000-15845000, due to being absent in the computeMatrix output.
Skipping chr17:45262500-45267500, due to being absent in the computeMatrix output.
Skipping chr17:56502500-56507500, due to being absent in the computeMatrix output.
Skipping chr17:57122500-57127500, due to being absent in the computeMatrix output.
Skipping chr17:68265000-68270000, due to being absent in the computeMatrix output.
Skipping chr17:78282500-78287500, due to being absent in the computeMatrix output.
Skipping chr18:47092500-47097500, due to being absent in the computeMatrix output.
Skipping chr18:48242500-48247500, due to being absent in the computeMatrix output.
Skipping chr2:10702500-10707500, due to being absent in the computeMatrix output.
Skipping chr2:27745000-27750000, due to being absent in the computeMatrix output.
Skipping chr2:46055000-46060000, due to being absent in the computeMatrix output.
Skipping chr2:47852500-47857500, due to being absent in the computeMatrix output.
Skipping chr2:59442500-59447500, due to being absent in the computeMatrix output.
Skipping chr2:64662500-64667500, due to being absent in the computeMatrix output.
Skipping chr2:230832500-230837500, due to being absent in the computeMatrix output.
Skipping chr20:19892500-19897500, due to being absent in the computeMatrix output.
Skipping chr20:49342500-49347500, due to being absent in the computeMatrix output.
Skipping chr20:59232500-59237500, due to being absent in the computeMatrix output.
Skipping chr21:27710000-27715000, due to being absent in the computeMatrix output.
Skipping chr22:24332500-24337500, due to being absent in the computeMatrix output.
Skipping chr3:45095000-45100000, due to being absent in the computeMatrix output.
Skipping chr3:122395000-122400000, due to being absent in the computeMatrix output.
Skipping chr3:122460000-122465000, due to being absent in the computeMatrix output.
Skipping chr3:150360000-150365000, due to being absent in the computeMatrix output.
Skipping chr3:193962500-193967500, due to being absent in the computeMatrix output.
Skipping chr3:196075000-196080000, due to being absent in the computeMatrix output.
Skipping chr4:6800000-6805000, due to being absent in the computeMatrix output.
Skipping chr4:40732500-40737500, due to being absent in the computeMatrix output.
Skipping chr4:47692500-47697500, due to being absent in the computeMatrix output.
Skipping chr4:53755000-53760000, due to being absent in the computeMatrix output.
Skipping chr4:119315000-119320000, due to being absent in the computeMatrix output.
Skipping chr4:139170000-139175000, due to being absent in the computeMatrix output.
Skipping chr4:142735000-142740000, due to being absent in the computeMatrix output.
Skipping chr6:30242500-30247500, due to being absent in the computeMatrix output.
Skipping chr6:80602500-80607500, due to being absent in the computeMatrix output.
Skipping chr6:125782500-125787500, due to being absent in the computeMatrix output.
Skipping chr6:136652500-136657500, due to being absent in the computeMatrix output.
Skipping chr6:150412500-150417500, due to being absent in the computeMatrix output.
Skipping chr7:35185000-35190000, due to being absent in the computeMatrix output.
Skipping chr7:38122500-38127500, due to being absent in the computeMatrix output.
Skipping chr7:54850000-54855000, due to being absent in the computeMatrix output.
Skipping chr7:106545000-106550000, due to being absent in the computeMatrix output.
Skipping chr8:57192500-57197500, due to being absent in the computeMatrix output.
Skipping chr9:124545000-124550000, due to being absent in the computeMatrix output.
Skipping chr9:131182500-131187500, due to being absent in the computeMatrix output.
Skipping chr9:132660000-132665000, due to being absent in the computeMatrix output.
Skipping chrX:7075000-7080000, due to being absent in the computeMatrix output.
Skipping chr1:11340000-11345000, due to being absent in the computeMatrix output.
Skipping chr1:178312500-178317500, due to being absent in the computeMatrix output.
Skipping chr1:183662500-183667500, due to being absent in the computeMatrix output.
Skipping chr1:220282500-220287500, due to being absent in the computeMatrix output.
Skipping chr1:227482500-227487500, due to being absent in the computeMatrix output.
Skipping chr10:80385000-80390000, due to being absent in the computeMatrix output.
Skipping chr10:84362500-84367500, due to being absent in the computeMatrix output.
Skipping chr11:12312500-12317500, due to being absent in the computeMatrix output.
Skipping chr11:14912500-14917500, due to being absent in the computeMatrix output.
Skipping chr11:19302500-19307500, due to being absent in the computeMatrix output.
Skipping chr11:44112500-44117500, due to being absent in the computeMatrix output.
Skipping chr13:29772500-29777500, due to being absent in the computeMatrix output.
Skipping chr14:35142500-35147500, due to being absent in the computeMatrix output.
Skipping chr15:84850000-84855000, due to being absent in the computeMatrix output.
Skipping chr2:11472500-11477500, due to being absent in the computeMatrix output.
Skipping chr2:18522500-18527500, due to being absent in the computeMatrix output.
Skipping chr2:47900000-47905000, due to being absent in the computeMatrix output.
Skipping chr2:60085000-60090000, due to being absent in the computeMatrix output.
Skipping chr20:4002500-4007500, due to being absent in the computeMatrix output.
Skipping chr22:23992500-23997500, due to being absent in the computeMatrix output.
Skipping chr22:30112500-30117500, due to being absent in the computeMatrix output.
Skipping chr22:41740000-41745000, due to being absent in the computeMatrix output.
Skipping chr4:1142500-1147500, due to being absent in the computeMatrix output.
Skipping chr5:35222500-35227500, due to being absent in the computeMatrix output.
Skipping chr5:131592500-131597500, due to being absent in the computeMatrix output.
Skipping chr6:52702500-52707500, due to being absent in the computeMatrix output.
Skipping chr6:70222500-70227500, due to being absent in the computeMatrix output.
Skipping chr6:160790000-160795000, due to being absent in the computeMatrix output.
Skipping chr7:128612500-128617500, due to being absent in the computeMatrix output.
Skipping chr7:151562500-151567500, due to being absent in the computeMatrix output.
Skipping chr8:29180000-29185000, due to being absent in the computeMatrix output.
Skipping chr11:10512500-10517500, due to being absent in the computeMatrix output.
Skipping chr3:169042500-169047500, due to being absent in the computeMatrix output.
Skipping chr8:30192500-30197500, due to being absent in the computeMatrix output.
Skipping chr1:23272500-23277500, due to being absent in the computeMatrix output.
Skipping chr1:160962500-160967500, due to being absent in the computeMatrix output.
Skipping chr1:178742500-178747500, due to being absent in the computeMatrix output.
Skipping chr1:211662500-211667500, due to being absent in the computeMatrix output.
Skipping chr1:212772500-212777500, due to being absent in the computeMatrix output.
Skipping chr1:245992500-245997500, due to being absent in the computeMatrix output.
Skipping chr10:34072500-34077500, due to being absent in the computeMatrix output.
Skipping chr10:50040000-50045000, due to being absent in the computeMatrix output.
Skipping chr10:73062500-73067500, due to being absent in the computeMatrix output.
Skipping chr10:84362500-84367500_r1, due to being absent in the computeMatrix output.
Skipping chr10:95832500-95837500, due to being absent in the computeMatrix output.
Skipping chr11:5812500-5817500, due to being absent in the computeMatrix output.
Skipping chr11:11012500-11017500, due to being absent in the computeMatrix output.
Skipping chr11:69505000-69510000, due to being absent in the computeMatrix output.
Skipping chr11:74172500-74177500, due to being absent in the computeMatrix output.
Skipping chr11:78952500-78957500, due to being absent in the computeMatrix output.
Skipping chr11:113722500-113727500, due to being absent in the computeMatrix output.
Skipping chr12:42572500-42577500, due to being absent in the computeMatrix output.
Skipping chr12:119882500-119887500, due to being absent in the computeMatrix output.
Skipping chr14:49832500-49837500, due to being absent in the computeMatrix output.
Skipping chr14:77552500-77557500, due to being absent in the computeMatrix output.
Skipping chr15:63095000-63100000, due to being absent in the computeMatrix output.
Skipping chr15:97240000-97245000, due to being absent in the computeMatrix output.
Skipping chr17:44672500-44677500, due to being absent in the computeMatrix output.
Skipping chr17:65382500-65387500, due to being absent in the computeMatrix output.
Skipping chr18:13152500-13157500, due to being absent in the computeMatrix output.
Skipping chr18:35952500-35957500, due to being absent in the computeMatrix output.
Skipping chr19:18510000-18515000, due to being absent in the computeMatrix output.
Skipping chr19:52240000-52245000, due to being absent in the computeMatrix output.
Skipping chr2:44470000-44475000, due to being absent in the computeMatrix output.
Skipping chr2:63032500-63037500, due to being absent in the computeMatrix output.
Skipping chr2:72572500-72577500, due to being absent in the computeMatrix output.
Skipping chr2:73182500-73187500, due to being absent in the computeMatrix output.
Skipping chr2:131335000-131340000, due to being absent in the computeMatrix output.
Skipping chr2:173752500-173757500, due to being absent in the computeMatrix output.
Skipping chr20:19892500-19897500_r1, due to being absent in the computeMatrix output.
Skipping chr22:35925000-35930000, due to being absent in the computeMatrix output.
Skipping chr3:127965000-127970000, due to being absent in the computeMatrix output.
Skipping chr3:134292500-134297500, due to being absent in the computeMatrix output.
Skipping chr3:185482500-185487500, due to being absent in the computeMatrix output.
Skipping chr3:188642500-188647500, due to being absent in the computeMatrix output.
Skipping chr3:188282500-188287500, due to being absent in the computeMatrix output.
Skipping chr3:193965000-193970000, due to being absent in the computeMatrix output.
Skipping chr4:75842500-75847500, due to being absent in the computeMatrix output.
Skipping chr4:99885000-99890000, due to being absent in the computeMatrix output.
Skipping chr4:123582500-123587500, due to being absent in the computeMatrix output.
Skipping chr5:75682500-75687500, due to being absent in the computeMatrix output.
Skipping chr5:135732500-135737500, due to being absent in the computeMatrix output.
Skipping chr5:140712500-140717500, due to being absent in the computeMatrix output.
Skipping chr5:142552500-142557500, due to being absent in the computeMatrix output.
Skipping chr6:24382500-24387500, due to being absent in the computeMatrix output.
Skipping chr6:53950000-53955000, due to being absent in the computeMatrix output.
Skipping chr6:81962500-81967500, due to being absent in the computeMatrix output.
Skipping chr6:106810000-106815000, due to being absent in the computeMatrix output.
Skipping chr6:106980000-106985000, due to being absent in the computeMatrix output.
Skipping chr6:106555000-106560000, due to being absent in the computeMatrix output.
Skipping chr6:139862500-139867500, due to being absent in the computeMatrix output.
Skipping chr6:139655000-139660000, due to being absent in the computeMatrix output.
Skipping chr6:139722500-139727500, due to being absent in the computeMatrix output.
Skipping chr6:147972500-147977500, due to being absent in the computeMatrix output.
Skipping chr6:158962500-158967500, due to being absent in the computeMatrix output.
Skipping chr7:20202500-20207500, due to being absent in the computeMatrix output.
Skipping chr7:23425000-23430000, due to being absent in the computeMatrix output.
Skipping chr7:37105000-37110000, due to being absent in the computeMatrix output.
Skipping chr8:23582500-23587500, due to being absent in the computeMatrix output.
Skipping chr8:43692500-43697500, due to being absent in the computeMatrix output.
Skipping chr8:67485000-67490000, due to being absent in the computeMatrix output.
Skipping chr8:95242500-95247500, due to being absent in the computeMatrix output.
Skipping chr8:125822500-125827500, due to being absent in the computeMatrix output.
Skipping chr9:4735000-4740000, due to being absent in the computeMatrix output.
Skipping chr9:90652500-90657500, due to being absent in the computeMatrix output.
Skipping chr9:92300000-92305000, due to being absent in the computeMatrix output.
Skipping chrX:15642500-15647500, due to being absent in the computeMatrix output.
Skipping chr1:223912500-223917500, due to being absent in the computeMatrix output.
Skipping chr1:246462500-246467500, due to being absent in the computeMatrix output.
Skipping chr10:46582500-46587500, due to being absent in the computeMatrix output.
Skipping chr10:49772500-49777500, due to being absent in the computeMatrix output.
Skipping chr10:114442500-114447500, due to being absent in the computeMatrix output.
Skipping chr11:5195000-5200000, due to being absent in the computeMatrix output.
Skipping chr11:59432500-59437500, due to being absent in the computeMatrix output.
Skipping chr11:115312500-115317500, due to being absent in the computeMatrix output.
Skipping chr12:52332500-52337500, due to being absent in the computeMatrix output.
Skipping chr13:33532500-33537500, due to being absent in the computeMatrix output.
Skipping chr13:113382500-113387500, due to being absent in the computeMatrix output.
Skipping chr15:69220000-69225000, due to being absent in the computeMatrix output.
Skipping chr15:82992500-82997500, due to being absent in the computeMatrix output.
Skipping chr17:65405000-65410000, due to being absent in the computeMatrix output.
Skipping chr19:15970000-15975000, due to being absent in the computeMatrix output.
Skipping chr2:11452500-11457500, due to being absent in the computeMatrix output.
Skipping chr2:113382500-113387500, due to being absent in the computeMatrix output.
Skipping chr2:122452500-122457500, due to being absent in the computeMatrix output.
Skipping chr20:2442500-2447500, due to being absent in the computeMatrix output.
Skipping chr20:51602500-51607500, due to being absent in the computeMatrix output.
Skipping chr3:123262500-123267500, due to being absent in the computeMatrix output.
Skipping chr3:127965000-127970000_r1, due to being absent in the computeMatrix output.
Skipping chr3:139192500-139197500, due to being absent in the computeMatrix output.
Skipping chr4:81595000-81600000, due to being absent in the computeMatrix output.
Skipping chr5:59162500-59167500, due to being absent in the computeMatrix output.
Skipping chr5:59002500-59007500, due to being absent in the computeMatrix output.
Skipping chr5:68242500-68247500, due to being absent in the computeMatrix output.
Skipping chr6:33242500-33247500, due to being absent in the computeMatrix output.
Skipping chr6:133840000-133845000, due to being absent in the computeMatrix output.
Skipping chr6:139755000-139760000, due to being absent in the computeMatrix output.
Skipping chr7:1162500-1167500, due to being absent in the computeMatrix output.
Skipping chr7:51422500-51427500, due to being absent in the computeMatrix output.
Skipping chr7:55262500-55267500, due to being absent in the computeMatrix output.
Skipping chr8:97172500-97177500, due to being absent in the computeMatrix output.
Skipping chrX:53452500-53457500, due to being absent in the computeMatrix output.
Skipping chr10:49522500-49527500, due to being absent in the computeMatrix output.
Skipping chr11:59682500-59687500, due to being absent in the computeMatrix output.
Skipping chr14:92770000-92775000, due to being absent in the computeMatrix output.
Skipping chr2:171152500-171157500, due to being absent in the computeMatrix output.
Skipping chr21:35190000-35195000, due to being absent in the computeMatrix output.
Skipping chr3:188482500-188487500, due to being absent in the computeMatrix output.
Skipping chr4:186805000-186810000, due to being absent in the computeMatrix output.

In [21]:
import subprocess

subprocess.run([
    "plotHeatmap",
    "-m", "ctrl_ctcf_chromatin_signal_matrix.gz",
    "-out", "ctrl_ctcf_chromatin_signal_heatmap_labeled.png",
    "--colorMap", "RdBu_r",
    "--whatToShow", "heatmap and colorbar",
    "--zMin", "0",
    "--zMax", "200",
    "--refPointLabel", "Anchor center",
    "--regionsLabel", "CTCF_anchors",
    "--samplesLabel", "CTCF_signal",
    "--plotTitle", "CUT&TAG Signal Heatmap"
])

CompletedProcess(args=['plotHeatmap', '-m', 'ctrl_ctcf_chromatin_signal_matrix.gz', '-out', 'ctrl_ctcf_chromatin_signal_heatmap_labeled.png', '--colorMap', 'RdBu_r', '--whatToShow', 'heatmap and colorbar', '--zMin', '0', '--zMax', '200', '--refPointLabel', 'Anchor center', '--regionsLabel', 'CTCF_anchors', '--samplesLabel', 'CTCF_signal', '--plotTitle', 'CUT&TAG Signal Heatmap'], returncode=0)

In [7]:
# doing it individually 
# H3K27me3 - TSS upregulated

## using subprocess
import subprocess

result = subprocess.run([
    "computeMatrix", "reference-point",
    "--referencePoint", "center",
    "-b", "2500", "-a", "2500",
    "-R", "/usr/users/papantonis1/aman/rnaseq_data/upregulated_transcript_level_TSS.bed",
    "-S", "/usr/users/papantonis1/aman/microc_data/cut_n_tag/nadine_cut_tag/nadine_cut_tag/C_H3K27me3_results/Aligned_files/Bigwig_scaled/CPI_H3K27me3.bw_RPGC.bw",
    "--skipZeros",
    "--missingDataAsZero",
    "-out", "ctrl_H3K27me3_TSS_matrix.gz",
    "--outFileSortedRegions", "ctrl_H3K27me3_TSS_sorted.bed"
], capture_output=True, text=True)

print(result.stdout)
print("STDERR:", result.stderr)
if result.returncode != 0:
    print("Error: computeMatrix failed")

STDERR: Skipping ENST00000544305.5, due to being absent in the computeMatrix output.
Skipping ENST00000374630.8, due to being absent in the computeMatrix output.
Skipping ENST00000400191.7, due to being absent in the computeMatrix output.
Skipping ENST00000374632.7, due to being absent in the computeMatrix output.
Skipping ENST00000633167.1, due to being absent in the computeMatrix output.
Skipping ENST00000373836.4, due to being absent in the computeMatrix output.
Skipping ENST00000632964.1, due to being absent in the computeMatrix output.
Skipping ENST00000310955.11, due to being absent in the computeMatrix output.
Skipping ENST00000372462.1, due to being absent in the computeMatrix output.
Skipping ENST00000478882.1, due to being absent in the computeMatrix output.
Skipping ENST00000641455.1, due to being absent in the computeMatrix output.
Skipping ENST00000462520.5, due to being absent in the computeMatrix output.
Skipping ENST00000368918.8, due to being absent in the computeMatrix output.
Skipping ENST00000489549.5, due to being absent in the computeMatrix output.
Skipping ENST00000486076.5, due to being absent in the computeMatrix output.
Skipping ENST00000368916.1, due to being absent in the computeMatrix output.
Skipping ENST00000493293.5, due to being absent in the computeMatrix output.
Skipping ENST00000264144.5, due to being absent in the computeMatrix output.
Skipping ENST00000461729.1, due to being absent in the computeMatrix output.
Skipping ENST00000661878.1, due to being absent in the computeMatrix output.
Skipping ENST00000366837.5, due to being absent in the computeMatrix output.
Skipping ENST00000467015.1, due to being absent in the computeMatrix output.
Skipping ENST00000485149.1, due to being absent in the computeMatrix output.
Skipping ENST00000466471.1, due to being absent in the computeMatrix output.
Skipping ENST00000634564.1, due to being absent in the computeMatrix output.
Skipping ENST00000636014.1, due to being absent in the computeMatrix output.
Skipping ENST00000422669.1, due to being absent in the computeMatrix output.
Skipping ENST00000489740.1, due to being absent in the computeMatrix output.
Skipping ENST00000611847.1, due to being absent in the computeMatrix output.
Skipping ENST00000446622.5, due to being absent in the computeMatrix output.
Skipping ENST00000426233.1, due to being absent in the computeMatrix output.
Skipping ENST00000479093.5, due to being absent in the computeMatrix output.
Skipping ENST00000467388.1, due to being absent in the computeMatrix output.
Skipping ENST00000459796.1, due to being absent in the computeMatrix output.
Skipping ENST00000442048.3, due to being absent in the computeMatrix output.
Skipping ENST00000478734.1, due to being absent in the computeMatrix output.
Skipping ENST00000282388.4, due to being absent in the computeMatrix output.
Skipping ENST00000474331.1, due to being absent in the computeMatrix output.
Skipping ENST00000432738.5, due to being absent in the computeMatrix output.
Skipping ENST00000397056.1, due to being absent in the computeMatrix output.
Skipping ENST00000616727.4, due to being absent in the computeMatrix output.
Skipping ENST00000478191.1, due to being absent in the computeMatrix output.
Skipping ENST00000471357.1, due to being absent in the computeMatrix output.
Skipping ENST00000476015.1, due to being absent in the computeMatrix output.
Skipping ENST00000486686.1, due to being absent in the computeMatrix output.
Skipping ENST00000513238.5, due to being absent in the computeMatrix output.
Skipping ENST00000307428.7, due to being absent in the computeMatrix output.
Skipping ENST00000265018.4, due to being absent in the computeMatrix output.
Skipping ENST00000483470.1, due to being absent in the computeMatrix output.
Skipping ENST00000481352.6, due to being absent in the computeMatrix output.
Skipping ENST00000512472.5, due to being absent in the computeMatrix output.
Skipping ENST00000372344.6, due to being absent in the computeMatrix output.
Skipping ENST00000642195.1, due to being absent in the computeMatrix output.
Skipping ENST00000643799.1, due to being absent in the computeMatrix output.
Skipping ENST00000304004.7, due to being absent in the computeMatrix output.
Skipping ENST00000646700.1, due to being absent in the computeMatrix output.
Skipping ENST00000646433.1, due to being absent in the computeMatrix output.
Skipping ENST00000607635.2, due to being absent in the computeMatrix output.
Skipping ENST00000645141.1, due to being absent in the computeMatrix output.
Skipping ENST00000488601.6, due to being absent in the computeMatrix output.
Skipping ENST00000643341.1, due to being absent in the computeMatrix output.
Skipping ENST00000423780.1, due to being absent in the computeMatrix output.
Skipping ENST00000455605.2, due to being absent in the computeMatrix output.
Skipping ENST00000514921.5, due to being absent in the computeMatrix output.
Skipping ENST00000274897.9, due to being absent in the computeMatrix output.
Skipping ENST00000370877.6, due to being absent in the computeMatrix output.
Skipping ENST00000509997.5, due to being absent in the computeMatrix output.
Skipping ENST00000461593.5, due to being absent in the computeMatrix output.
Skipping ENST00000468181.1, due to being absent in the computeMatrix output.
Skipping ENST00000485503.1, due to being absent in the computeMatrix output.
Skipping ENST00000404944.3, due to being absent in the computeMatrix output.
Skipping ENST00000617523.1, due to being absent in the computeMatrix output.
Skipping ENST00000522675.1, due to being absent in the computeMatrix output.
Skipping ENST00000518186.1, due to being absent in the computeMatrix output.
Skipping ENST00000524247.5, due to being absent in the computeMatrix output.
Skipping ENST00000480388.1, due to being absent in the computeMatrix output.
Skipping ENST00000482335.1, due to being absent in the computeMatrix output.
Skipping ENST00000465485.1, due to being absent in the computeMatrix output.
Skipping ENST00000605781.5, due to being absent in the computeMatrix output.
Skipping ENST00000490442.5, due to being absent in the computeMatrix output.
Skipping ENST00000478698.1, due to being absent in the computeMatrix output.
Skipping ENST00000370355.3, due to being absent in the computeMatrix output.
Skipping ENST00000493143.1, due to being absent in the computeMatrix output.
Skipping ENST00000633965.1, due to being absent in the computeMatrix output.
Skipping ENST00000484853.1, due to being absent in the computeMatrix output.
Skipping ENST00000531110.6, due to being absent in the computeMatrix output.
Skipping ENST00000525685.6, due to being absent in the computeMatrix output.
Skipping ENST00000534296.5, due to being absent in the computeMatrix output.
Skipping ENST00000525688.5, due to being absent in the computeMatrix output.
Skipping ENST00000278385.10, due to being absent in the computeMatrix output.
Skipping ENST00000533222.5, due to being absent in the computeMatrix output.
Skipping ENST00000525241.1, due to being absent in the computeMatrix output.
Skipping ENST00000524922.1, due to being absent in the computeMatrix output.
Skipping ENST00000525348.1, due to being absent in the computeMatrix output.
Skipping ENST00000526553.6, due to being absent in the computeMatrix output.
Skipping ENST00000534082.1, due to being absent in the computeMatrix output.
Skipping ENST00000525293.5, due to being absent in the computeMatrix output.
Skipping ENST00000528672.1, due to being absent in the computeMatrix output.
Skipping ENST00000532339.1, due to being absent in the computeMatrix output.
Skipping ENST00000527326.1, due to being absent in the computeMatrix output.
Skipping ENST00000531141.1, due to being absent in the computeMatrix output.
Skipping ENST00000525469.1, due to being absent in the computeMatrix output.
Skipping ENST00000533860.5, due to being absent in the computeMatrix output.
Skipping ENST00000530493.1, due to being absent in the computeMatrix output.
Skipping ENST00000525604.1, due to being absent in the computeMatrix output.
Skipping ENST00000528503.1, due to being absent in the computeMatrix output.
Skipping ENST00000531563.1, due to being absent in the computeMatrix output.
Skipping ENST00000550574.1, due to being absent in the computeMatrix output.
Skipping ENST00000548553.1, due to being absent in the computeMatrix output.
Skipping ENST00000550502.1, due to being absent in the computeMatrix output.
Skipping ENST00000695929.1, due to being absent in the computeMatrix output.
Skipping ENST00000547104.1, due to being absent in the computeMatrix output.
Skipping ENST00000332160.5, due to being absent in the computeMatrix output.
Skipping ENST00000550097.1, due to being absent in the computeMatrix output.
Skipping ENST00000549922.1, due to being absent in the computeMatrix output.
Skipping ENST00000546840.3, due to being absent in the computeMatrix output.
Skipping ENST00000228515.6, due to being absent in the computeMatrix output.
Skipping ENST00000548206.1, due to being absent in the computeMatrix output.
Skipping ENST00000548981.5, due to being absent in the computeMatrix output.
Skipping ENST00000552899.5, due to being absent in the computeMatrix output.
Skipping ENST00000546935.5, due to being absent in the computeMatrix output.
Skipping ENST00000552680.1, due to being absent in the computeMatrix output.
Skipping ENST00000550461.1, due to being absent in the computeMatrix output.
Skipping ENST00000559966.1, due to being absent in the computeMatrix output.
Skipping ENST00000562974.1, due to being absent in the computeMatrix output.
Skipping ENST00000566720.5, due to being absent in the computeMatrix output.
Skipping ENST00000566883.5, due to being absent in the computeMatrix output.
Skipping ENST00000566917.1, due to being absent in the computeMatrix output.
Skipping ENST00000565655.1, due to being absent in the computeMatrix output.
Skipping ENST00000566823.1, due to being absent in the computeMatrix output.
Skipping ENST00000678148.1, due to being absent in the computeMatrix output.
Skipping ENST00000572830.5, due to being absent in the computeMatrix output.
Skipping ENST00000570519.5, due to being absent in the computeMatrix output.
Skipping ENST00000576427.1, due to being absent in the computeMatrix output.
Skipping ENST00000576269.1, due to being absent in the computeMatrix output.
Skipping ENST00000576460.5, due to being absent in the computeMatrix output.
Skipping ENST00000572033.1, due to being absent in the computeMatrix output.
Skipping ENST00000574157.5, due to being absent in the computeMatrix output.
Skipping ENST00000572932.1, due to being absent in the computeMatrix output.
Skipping ENST00000573635.1, due to being absent in the computeMatrix output.
Skipping ENST00000570732.2, due to being absent in the computeMatrix output.
Skipping ENST00000570346.1, due to being absent in the computeMatrix output.
Skipping ENST00000570939.2, due to being absent in the computeMatrix output.
Skipping ENST00000573672.1, due to being absent in the computeMatrix output.
Skipping ENST00000571826.5, due to being absent in the computeMatrix output.
Skipping ENST00000572134.1, due to being absent in the computeMatrix output.
Skipping ENST00000575237.2, due to being absent in the computeMatrix output.
Skipping ENST00000634839.1, due to being absent in the computeMatrix output.
Skipping ENST00000636002.1, due to being absent in the computeMatrix output.
Skipping ENST00000636895.1, due to being absent in the computeMatrix output.
Skipping ENST00000593890.1, due to being absent in the computeMatrix output.
Skipping ENST00000248244.6, due to being absent in the computeMatrix output.
Skipping ENST00000597211.1, due to being absent in the computeMatrix output.
Skipping ENST00000464867.1, due to being absent in the computeMatrix output.
Skipping ENST00000415997.1, due to being absent in the computeMatrix output.
Skipping ENST00000491395.5, due to being absent in the computeMatrix output.
Skipping ENST00000463070.1, due to being absent in the computeMatrix output.
Skipping ENST00000548570.1, due to being absent in the computeMatrix output.
Skipping ENST00000462267.1, due to being absent in the computeMatrix output.
Skipping ENST00000467731.1, due to being absent in the computeMatrix output.
Skipping ENST00000474001.1, due to being absent in the computeMatrix output.
Skipping ENST00000491387.1, due to being absent in the computeMatrix output.
Skipping ENST00000381565.2, due to being absent in the computeMatrix output.
Skipping ENST00000308521.10, due to being absent in the computeMatrix output.
Skipping ENST00000684963.1, due to being absent in the computeMatrix output.
Skipping ENST00000470741.1, due to being absent in the computeMatrix output.
Skipping ENST00000691918.1, due to being absent in the computeMatrix output.
Skipping ENST00000693639.1, due to being absent in the computeMatrix output.
Skipping ENST00000693646.1, due to being absent in the computeMatrix output.
Skipping ENST00000693157.1, due to being absent in the computeMatrix output.
Skipping ENST00000590447.1, due to being absent in the computeMatrix output.
Skipping ENST00000440023.5, due to being absent in the computeMatrix output.
Skipping ENST00000432467.1, due to being absent in the computeMatrix output.
Skipping ENST00000370274.8, due to being absent in the computeMatrix output.
Skipping ENST00000479015.1, due to being absent in the computeMatrix output.
Skipping ENST00000461865.1, due to being absent in the computeMatrix output.
Skipping ENST00000304758.5, due to being absent in the computeMatrix output.
Skipping ENST00000371959.9, due to being absent in the computeMatrix output.
Skipping ENST00000462114.1, due to being absent in the computeMatrix output.
Skipping ENST00000576342.2, due to being absent in the computeMatrix output.
Skipping ENST00000421473.6, due to being absent in the computeMatrix output.
Skipping ENST00000413547.5, due to being absent in the computeMatrix output.
Skipping ENST00000419551.5, due to being absent in the computeMatrix output.
Skipping ENST00000454620.1, due to being absent in the computeMatrix output.
Skipping ENST00000342322.8, due to being absent in the computeMatrix output.
Skipping ENST00000420414.5, due to being absent in the computeMatrix output.
Skipping ENST00000552082.2, due to being absent in the computeMatrix output.
Skipping ENST00000473966.1, due to being absent in the computeMatrix output.
Skipping ENST00000383516.8, due to being absent in the computeMatrix output.
Skipping ENST00000470816.5, due to being absent in the computeMatrix output.
Skipping ENST00000496799.1, due to being absent in the computeMatrix output.
Skipping ENST00000383515.6, due to being absent in the computeMatrix output.
Skipping ENST00000475107.1, due to being absent in the computeMatrix output.
Skipping ENST00000494169.1, due to being absent in the computeMatrix output.
Skipping ENST00000454646.5, due to being absent in the computeMatrix output.
Skipping ENST00000488237.5, due to being absent in the computeMatrix output.
Skipping ENST00000472371.1, due to being absent in the computeMatrix output.
Skipping ENST00000496199.1, due to being absent in the computeMatrix output.
Skipping ENST00000458026.1, due to being absent in the computeMatrix output.
Skipping ENST00000422674.6, due to being absent in the computeMatrix output.
Skipping ENST00000435546.5, due to being absent in the computeMatrix output.
Skipping ENST00000420400.5, due to being absent in the computeMatrix output.
Skipping ENST00000453350.1, due to being absent in the computeMatrix output.
Skipping ENST00000435971.6, due to being absent in the computeMatrix output.
Skipping ENST00000485195.5, due to being absent in the computeMatrix output.
Skipping ENST00000428775.1, due to being absent in the computeMatrix output.
Skipping ENST00000471879.1, due to being absent in the computeMatrix output.
Skipping ENST00000493561.1, due to being absent in the computeMatrix output.
Skipping ENST00000467947.1, due to being absent in the computeMatrix output.
Skipping ENST00000484138.1, due to being absent in the computeMatrix output.
Skipping ENST00000470224.1, due to being absent in the computeMatrix output.
Skipping ENST00000467347.1, due to being absent in the computeMatrix output.
Skipping ENST00000469743.1, due to being absent in the computeMatrix output.
Skipping ENST00000464106.1, due to being absent in the computeMatrix output.
Skipping ENST00000464841.5, due to being absent in the computeMatrix output.
Skipping ENST00000464400.1, due to being absent in the computeMatrix output.
Skipping ENST00000462141.1, due to being absent in the computeMatrix output.
Skipping ENST00000420949.6, due to being absent in the computeMatrix output.
Skipping ENST00000488552.1, due to being absent in the computeMatrix output.
Skipping ENST00000472771.1, due to being absent in the computeMatrix output.
Skipping ENST00000490256.5, due to being absent in the computeMatrix output.
Skipping ENST00000469365.1, due to being absent in the computeMatrix output.
Skipping ENST00000468706.1, due to being absent in the computeMatrix output.
Skipping ENST00000461975.1, due to being absent in the computeMatrix output.
Skipping ENST00000486266.5, due to being absent in the computeMatrix output.
Skipping ENST00000494158.5, due to being absent in the computeMatrix output.
Skipping ENST00000496419.5, due to being absent in the computeMatrix output.
Skipping ENST00000423509.6, due to being absent in the computeMatrix output.
Skipping ENST00000430940.6, due to being absent in the computeMatrix output.
Skipping ENST00000422726.6, due to being absent in the computeMatrix output.
Skipping ENST00000476248.5, due to being absent in the computeMatrix output.
Skipping ENST00000424832.6, due to being absent in the computeMatrix output.
Skipping ENST00000621261.1, due to being absent in the computeMatrix output.
Skipping ENST00000640223.1, due to being absent in the computeMatrix output.
Skipping ENST00000464914.5, due to being absent in the computeMatrix output.
Skipping ENST00000457806.1, due to being absent in the computeMatrix output.
Skipping ENST00000462851.1, due to being absent in the computeMatrix output.
Skipping ENST00000497204.1, due to being absent in the computeMatrix output.
Skipping ENST00000472294.5, due to being absent in the computeMatrix output.
Skipping ENST00000473379.5, due to being absent in the computeMatrix output.
Skipping ENST00000416726.5, due to being absent in the computeMatrix output.
Skipping ENST00000425848.6, due to being absent in the computeMatrix output.
Skipping ENST00000490676.1, due to being absent in the computeMatrix output.
Skipping ENST00000461583.5, due to being absent in the computeMatrix output.
Skipping ENST00000470915.1, due to being absent in the computeMatrix output.
Skipping ENST00000445222.1, due to being absent in the computeMatrix output.
Skipping ENST00000422711.5, due to being absent in the computeMatrix output.
Skipping ENST00000447400.5, due to being absent in the computeMatrix output.
Skipping ENST00000551832.2, due to being absent in the computeMatrix output.
Skipping ENST00000487648.1, due to being absent in the computeMatrix output.
Skipping ENST00000428296.6, due to being absent in the computeMatrix output.
Skipping ENST00000490333.5, due to being absent in the computeMatrix output.
Skipping ENST00000494850.1, due to being absent in the computeMatrix output.
Skipping ENST00000420067.5, due to being absent in the computeMatrix output.
Skipping ENST00000483651.1, due to being absent in the computeMatrix output.
Skipping ENST00000494940.1, due to being absent in the computeMatrix output.
Skipping ENST00000420923.5, due to being absent in the computeMatrix output.
Skipping ENST00000489795.5, due to being absent in the computeMatrix output.
Skipping ENST00000482336.1, due to being absent in the computeMatrix output.

In [8]:
subprocess.run([
    "plotHeatmap",
    "-m", "ctrl_H3K27me3_TSS_matrix.gz",
    "-out", "ctrl_H3K27me3_TSS_heatmap.png",
    "--colorMap", "RdBu_r",
    "--whatToShow", "heatmap and colorbar",
    "--zMin", "0",
    "--zMax", "200",
    "--refPointLabel", "TSS",
    "--regionsLabel", "Upregulated_TSS",
    "--samplesLabel", "H3K27me3_signal",
    "--plotTitle", "H3K27me3 Signal at Upregulated TSSs (CTRL)"
])

CompletedProcess(args=['plotHeatmap', '-m', 'ctrl_H3K27me3_TSS_matrix.gz', '-out', 'ctrl_H3K27me3_TSS_heatmap.png', '--colorMap', 'RdBu_r', '--whatToShow', 'heatmap and colorbar', '--zMin', '0', '--zMax', '200', '--refPointLabel', 'TSS', '--regionsLabel', 'Upregulated_TSS', '--samplesLabel', 'H3K27me3_signal', '--plotTitle', 'H3K27me3 Signal at Upregulated TSSs (CTRL)'], returncode=0)