In [1]:
import pandas as pd
from pybedtools import BedTool

In [4]:
# import all loops
all_loops = pd.read_csv("/usr/users/papantonis1/aman/microc_project/loop_calling_premade_hic/jupyter_notes/ml_3_multiclassmodel.csv")
all_loops = all_loops.drop(columns=["Unnamed: 0"])
all_loops

,chr1,start1,end1,chr2,start2,end2,status,ctrl_signal,rbp1_signal,log2FC,...,distance,loop_id,comp_switch_A1,comp_switch_A2,loop_class,source,CTCF_signal,H3K27me3_signal,H3K4me3_signal,rad21_signal
0,chr1,1952500,1957500,chr1,2042500,2047500,shared,NaN,NaN,0.000000,...,90000,0,NaN,NaN,uncategorized,ctrl,3.719732,1.930504,0.188543,0.024018
1,chr1,2202500,2207500,chr1,2382500,2387500,shared,NaN,NaN,0.000000,...,180000,1,NaN,NaN,uncategorized,ctrl,62.158684,1.542050,0.566125,0.063427
2,chr1,2412500,2417500,chr1,2552500,2557500,shared,NaN,NaN,0.000000,...,140000,2,NaN,NaN,uncategorized,ctrl,13.704273,4.520206,0.188543,0.044699
3,chr1,3490000,3495000,chr1,3615000,3620000,shared,NaN,NaN,0.000000,...,125000,3,NaN,NaN,uncategorized,ctrl,1.076765,5.414830,0.188543,0.024769
4,chr1,3565000,3570000,chr1,3615000,3620000,shared,NaN,NaN,0.000000,...,50000,4,NaN,NaN,uncategorized,ctrl,16.477770,1.377250,0.188543,0.042592
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32272,chrY,10945000,10950000,chrY,11290000,11295000,gained,0.006078,0.006342,0.061177,...,345000,32272,stable,stable,intra-TAD,rbp1,0.000000,0.000000,0.188543,0.026824
32273,chrY,10982500,10987500,chrY,11292500,11297500,gained,0.007661,0.005159,-0.570544,...,310000,32273,stable,stable,intra-TAD,rbp1,0.522068,0.188342,0.249019,0.130330
32274,chrY,11292500,11297500,chrY,11722500,11727500,gained,0.001017,0.001021,0.005836,...,430000,32274,stable,stable,uncategorized,rbp1,0.261034,0.082400,0.241160,0.123878
32275,chrY,11530000,11535000,chrY,11760000,11765000,gained,0.004674,0.006621,0.502513,...,230000,32275,stable,stable,intra-TAD,rbp1,0.293663,0.188342,0.214433,0.112741
32276,chrY,19432500,19437500,chrY,20742500,20747500,gained,0.007706,0.016045,1.058072,...,1310000,32276,stable,stable,uncategorized,rbp1,1.533574,0.176571,0.188543,0.020762

In [7]:
# Save left anchor BED
all_loops[['chr1', 'start1', 'end1']].to_csv("ml_3_multiclassmodel_left_anchors.bed", sep='\t', header=False, index=False)

# Save right anchor BED
all_loops[['chr2', 'start2', 'end2']].to_csv("ml_3_multiclassmodel_right_anchors.bed", sep='\t', header=False, index=False)

In [8]:
# refgen
genome_fasta = "/usr/users/papantonis1/aman/microc_project/refgen/hg38.fa"

In [9]:
# Left
left_bt = BedTool("ml_3_multiclassmodel_left_anchors.bed")
left_gc = left_bt.nucleotide_content(fi=genome_fasta).to_dataframe()
left_gc

,chrom,start,end,name,score,strand,thickStart,thickEnd,itemRgb,blockCount,blockSizes,blockStarts
0,#1_usercol,2_usercol,3_usercol,4_pct_at,5_pct_gc,6_num_A,7_num_C,8_num_G,9_num_T,10_num_N,11_num_oth,12_seq_len
1,chr1,1952500,1957500,0.447400,0.552600,1195,1376,1387,1042,0,0,5000
2,chr1,2202500,2207500,0.357600,0.642400,846,1734,1478,942,0,0,5000
3,chr1,2412500,2417500,0.352600,0.647400,816,1458,1779,947,0,0,5000
4,chr1,3490000,3495000,0.352400,0.647600,938,1726,1512,824,0,0,5000
...,...,...,...,...,...,...,...,...,...,...,...,...
32273,chrY,10945000,10950000,0.534200,0.465800,1091,2115,214,1580,0,0,5000
32274,chrY,10982500,10987500,0.535400,0.459600,1032,2065,233,1645,25,0,5000
32275,chrY,11292500,11297500,0.537800,0.462200,1068,2041,270,1621,0,0,5000
32276,chrY,11530000,11535000,0.627200,0.372800,2081,410,1454,1055,0,0,5000
32277,chrY,19432500,19437500,0.585200,0.414800,1789,1013,1061,1137,0,0,5000

In [10]:
# Right
right_bt = BedTool("ml_3_multiclassmodel_right_anchors.bed")
right_gc = right_bt.nucleotide_content(fi=genome_fasta).to_dataframe()
right_gc

,chrom,start,end,name,score,strand,thickStart,thickEnd,itemRgb,blockCount,blockSizes,blockStarts
0,#1_usercol,2_usercol,3_usercol,4_pct_at,5_pct_gc,6_num_A,7_num_C,8_num_G,9_num_T,10_num_N,11_num_oth,12_seq_len
1,chr1,2042500,2047500,0.398000,0.602000,1116,1600,1410,874,0,0,5000
2,chr1,2382500,2387500,0.415400,0.584600,1019,1515,1408,1058,0,0,5000
3,chr1,2552500,2557500,0.342400,0.657600,787,1621,1667,925,0,0,5000
4,chr1,3615000,3620000,0.447200,0.552800,1231,1477,1287,1005,0,0,5000
...,...,...,...,...,...,...,...,...,...,...,...,...
32273,chrY,11290000,11295000,0.556800,0.443200,1140,1795,421,1644,0,0,5000
32274,chrY,11292500,11297500,0.537800,0.462200,1068,2041,270,1621,0,0,5000
32275,chrY,11722500,11727500,0.623200,0.376800,2039,360,1524,1077,0,0,5000
32276,chrY,11760000,11765000,0.615200,0.384800,1595,933,991,1481,0,0,5000
32277,chrY,20742500,20747500,0.559800,0.440200,1481,1067,1134,1318,0,0,5000

In [13]:
left_gc_clean = left_gc.iloc[1:].reset_index(drop=True)
right_gc_clean = right_gc.iloc[1:].reset_index(drop=True)

In [14]:
all_loops["GC_left"] = left_gc_clean["score"]
all_loops["GC_right"] = right_gc_clean["score"]
all_loops

,chr1,start1,end1,chr2,start2,end2,status,ctrl_signal,rbp1_signal,log2FC,...,comp_switch_A1,comp_switch_A2,loop_class,source,CTCF_signal,H3K27me3_signal,H3K4me3_signal,rad21_signal,GC_left,GC_right
0,chr1,1952500,1957500,chr1,2042500,2047500,shared,NaN,NaN,0.000000,...,NaN,NaN,uncategorized,ctrl,3.719732,1.930504,0.188543,0.024018,0.552600,0.602000
1,chr1,2202500,2207500,chr1,2382500,2387500,shared,NaN,NaN,0.000000,...,NaN,NaN,uncategorized,ctrl,62.158684,1.542050,0.566125,0.063427,0.642400,0.584600
2,chr1,2412500,2417500,chr1,2552500,2557500,shared,NaN,NaN,0.000000,...,NaN,NaN,uncategorized,ctrl,13.704273,4.520206,0.188543,0.044699,0.647400,0.657600
3,chr1,3490000,3495000,chr1,3615000,3620000,shared,NaN,NaN,0.000000,...,NaN,NaN,uncategorized,ctrl,1.076765,5.414830,0.188543,0.024769,0.647600,0.552800
4,chr1,3565000,3570000,chr1,3615000,3620000,shared,NaN,NaN,0.000000,...,NaN,NaN,uncategorized,ctrl,16.477770,1.377250,0.188543,0.042592,0.637000,0.552800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32272,chrY,10945000,10950000,chrY,11290000,11295000,gained,0.006078,0.006342,0.061177,...,stable,stable,intra-TAD,rbp1,0.000000,0.000000,0.188543,0.026824,0.465800,0.443200
32273,chrY,10982500,10987500,chrY,11292500,11297500,gained,0.007661,0.005159,-0.570544,...,stable,stable,intra-TAD,rbp1,0.522068,0.188342,0.249019,0.130330,0.459600,0.462200
32274,chrY,11292500,11297500,chrY,11722500,11727500,gained,0.001017,0.001021,0.005836,...,stable,stable,uncategorized,rbp1,0.261034,0.082400,0.241160,0.123878,0.462200,0.376800
32275,chrY,11530000,11535000,chrY,11760000,11765000,gained,0.004674,0.006621,0.502513,...,stable,stable,intra-TAD,rbp1,0.293663,0.188342,0.214433,0.112741,0.372800,0.384800
32276,chrY,19432500,19437500,chrY,20742500,20747500,gained,0.007706,0.016045,1.058072,...,stable,stable,uncategorized,rbp1,1.533574,0.176571,0.188543,0.020762,0.414800,0.440200

In [16]:
# convert to numeric
all_loops["GC_left"] = all_loops["GC_left"].astype(float)
all_loops["GC_right"] = all_loops["GC_right"].astype(float)

all_loops["GC_mean"] = (all_loops["GC_left"] + all_loops["GC_right"]) / 2
all_loops["GC_diff"] = (all_loops["GC_left"] - all_loops["GC_right"]).abs()
all_loops

,chr1,start1,end1,chr2,start2,end2,status,ctrl_signal,rbp1_signal,log2FC,...,loop_class,source,CTCF_signal,H3K27me3_signal,H3K4me3_signal,rad21_signal,GC_left,GC_right,GC_mean,GC_diff
0,chr1,1952500,1957500,chr1,2042500,2047500,shared,NaN,NaN,0.000000,...,uncategorized,ctrl,3.719732,1.930504,0.188543,0.024018,0.5526,0.6020,0.5773,0.0494
1,chr1,2202500,2207500,chr1,2382500,2387500,shared,NaN,NaN,0.000000,...,uncategorized,ctrl,62.158684,1.542050,0.566125,0.063427,0.6424,0.5846,0.6135,0.0578
2,chr1,2412500,2417500,chr1,2552500,2557500,shared,NaN,NaN,0.000000,...,uncategorized,ctrl,13.704273,4.520206,0.188543,0.044699,0.6474,0.6576,0.6525,0.0102
3,chr1,3490000,3495000,chr1,3615000,3620000,shared,NaN,NaN,0.000000,...,uncategorized,ctrl,1.076765,5.414830,0.188543,0.024769,0.6476,0.5528,0.6002,0.0948
4,chr1,3565000,3570000,chr1,3615000,3620000,shared,NaN,NaN,0.000000,...,uncategorized,ctrl,16.477770,1.377250,0.188543,0.042592,0.6370,0.5528,0.5949,0.0842
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32272,chrY,10945000,10950000,chrY,11290000,11295000,gained,0.006078,0.006342,0.061177,...,intra-TAD,rbp1,0.000000,0.000000,0.188543,0.026824,0.4658,0.4432,0.4545,0.0226
32273,chrY,10982500,10987500,chrY,11292500,11297500,gained,0.007661,0.005159,-0.570544,...,intra-TAD,rbp1,0.522068,0.188342,0.249019,0.130330,0.4596,0.4622,0.4609,0.0026
32274,chrY,11292500,11297500,chrY,11722500,11727500,gained,0.001017,0.001021,0.005836,...,uncategorized,rbp1,0.261034,0.082400,0.241160,0.123878,0.4622,0.3768,0.4195,0.0854
32275,chrY,11530000,11535000,chrY,11760000,11765000,gained,0.004674,0.006621,0.502513,...,intra-TAD,rbp1,0.293663,0.188342,0.214433,0.112741,0.3728,0.3848,0.3788,0.0120
32276,chrY,19432500,19437500,chrY,20742500,20747500,gained,0.007706,0.016045,1.058072,...,uncategorized,rbp1,1.533574,0.176571,0.188543,0.020762,0.4148,0.4402,0.4275,0.0254

In [17]:
all_loops = all_loops.drop(columns=["GC_left", "GC_right"])
all_loops

,chr1,start1,end1,chr2,start2,end2,status,ctrl_signal,rbp1_signal,log2FC,...,comp_switch_A1,comp_switch_A2,loop_class,source,CTCF_signal,H3K27me3_signal,H3K4me3_signal,rad21_signal,GC_mean,GC_diff
0,chr1,1952500,1957500,chr1,2042500,2047500,shared,NaN,NaN,0.000000,...,NaN,NaN,uncategorized,ctrl,3.719732,1.930504,0.188543,0.024018,0.5773,0.0494
1,chr1,2202500,2207500,chr1,2382500,2387500,shared,NaN,NaN,0.000000,...,NaN,NaN,uncategorized,ctrl,62.158684,1.542050,0.566125,0.063427,0.6135,0.0578
2,chr1,2412500,2417500,chr1,2552500,2557500,shared,NaN,NaN,0.000000,...,NaN,NaN,uncategorized,ctrl,13.704273,4.520206,0.188543,0.044699,0.6525,0.0102
3,chr1,3490000,3495000,chr1,3615000,3620000,shared,NaN,NaN,0.000000,...,NaN,NaN,uncategorized,ctrl,1.076765,5.414830,0.188543,0.024769,0.6002,0.0948
4,chr1,3565000,3570000,chr1,3615000,3620000,shared,NaN,NaN,0.000000,...,NaN,NaN,uncategorized,ctrl,16.477770,1.377250,0.188543,0.042592,0.5949,0.0842
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32272,chrY,10945000,10950000,chrY,11290000,11295000,gained,0.006078,0.006342,0.061177,...,stable,stable,intra-TAD,rbp1,0.000000,0.000000,0.188543,0.026824,0.4545,0.0226
32273,chrY,10982500,10987500,chrY,11292500,11297500,gained,0.007661,0.005159,-0.570544,...,stable,stable,intra-TAD,rbp1,0.522068,0.188342,0.249019,0.130330,0.4609,0.0026
32274,chrY,11292500,11297500,chrY,11722500,11727500,gained,0.001017,0.001021,0.005836,...,stable,stable,uncategorized,rbp1,0.261034,0.082400,0.241160,0.123878,0.4195,0.0854
32275,chrY,11530000,11535000,chrY,11760000,11765000,gained,0.004674,0.006621,0.502513,...,stable,stable,intra-TAD,rbp1,0.293663,0.188342,0.214433,0.112741,0.3788,0.0120
32276,chrY,19432500,19437500,chrY,20742500,20747500,gained,0.007706,0.016045,1.058072,...,stable,stable,uncategorized,rbp1,1.533574,0.176571,0.188543,0.020762,0.4275,0.0254

In [18]:
all_loops.to_csv("/usr/users/papantonis1/aman/microc_project/loop_calling_premade_hic/jupyter_notes/ml_4_multiclassmodel.csv")