In [1]:
import pandas as pd

ctrl_df = pd.read_csv("intra_inter_tad_ctrl.csv")
rbp1_df = pd.read_csv("intra_inter_tad_rbp1.csv")

In [2]:
print(ctrl_df.columns)
print(rbp1_df.columns)

Index(['Unnamed: 0', 'chr1', 'start1', 'end1', 'chr2', 'start2', 'end2',
       'tad_start_anchor1', 'tad_end_anchor1', 'tad_start_anchor2',
       'tad_end_anchor2', 'loop_class', 'loop_distance', 'loop_distance_kb',
       'tad_size_anchor1_kb', 'tad_size_anchor2_kb'],
      dtype='object')
Index(['Unnamed: 0', 'chr1', 'start1', 'end1', 'chr2', 'start2', 'end2',
       'tad_start_anchor1', 'tad_end_anchor1', 'tad_start_anchor2',
       'tad_end_anchor2', 'loop_class', 'loop_distance', 'loop_distance_kb',
       'tad_size_anchor1_kb', 'tad_size_anchor2_kb'],
      dtype='object')

In [3]:
ctrl_df

,Unnamed: 0,chr1,start1,end1,chr2,start2,end2,tad_start_anchor1,tad_end_anchor1,tad_start_anchor2,tad_end_anchor2,loop_class,loop_distance,loop_distance_kb,tad_size_anchor1_kb,tad_size_anchor2_kb
0,0,chr1,3912500,3917500,chr1,4592500,4597500,3900000.0,4030000.0,3900000.0,5380000.0,intra-TAD,680000,680.0,130.0,1480.0
1,1,chr1,5502500,5507500,chr1,5622500,5627500,3900000.0,5745000.0,5510000.0,5745000.0,intra-TAD,120000,120.0,1845.0,235.0
2,2,chr1,5502500,5507500,chr1,5742500,5747500,3900000.0,5745000.0,5635000.0,5745000.0,inter-TAD,240000,240.0,1845.0,110.0
3,3,chr1,5632500,5637500,chr1,5742500,5747500,5635000.0,5745000.0,5635000.0,5745000.0,inter-TAD,110000,110.0,110.0,110.0
4,4,chr1,5635000,5640000,chr1,5980000,5985000,5635000.0,5745000.0,NaN,NaN,uncategorized,345000,345.0,110.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19031,19031,chrY,10992500,10997500,chrY,11722500,11727500,10740000.0,11030000.0,NaN,NaN,uncategorized,730000,730.0,290.0,NaN
19032,19032,chrY,11302500,11307500,chrY,11722500,11727500,NaN,NaN,NaN,NaN,uncategorized,420000,420.0,NaN,NaN
19033,19033,chrY,11522500,11527500,chrY,11712500,11717500,11335000.0,11540000.0,NaN,NaN,uncategorized,190000,190.0,205.0,NaN
19034,19034,chrY,11525000,11530000,chrY,11680000,11685000,11335000.0,11540000.0,NaN,NaN,uncategorized,155000,155.0,205.0,NaN
19035,19035,chrY,20562500,20567500,chrY,20732500,20737500,20560000.0,20660000.0,20560000.0,20735000.0,inter-TAD,170000,170.0,100.0,175.0

In [4]:
rbp1_df

,Unnamed: 0,chr1,start1,end1,chr2,start2,end2,tad_start_anchor1,tad_end_anchor1,tad_start_anchor2,tad_end_anchor2,loop_class,loop_distance,loop_distance_kb,tad_size_anchor1_kb,tad_size_anchor2_kb
0,0,chr1,3910000,3915000,chr1,4065000,4070000,3900000.0,4800000.0,3900000.0,4800000.0,intra-TAD,155000,155.0,900.0,900.0
1,1,chr1,3910000,3915000,chr1,4155000,4160000,3900000.0,4800000.0,3900000.0,4800000.0,intra-TAD,245000,245.0,900.0,900.0
2,2,chr1,5502500,5507500,chr1,5622500,5627500,NaN,NaN,5510000.0,5745000.0,uncategorized,120000,120.0,NaN,235.0
3,3,chr1,5502500,5507500,chr1,5732500,5737500,NaN,NaN,5635000.0,5745000.0,uncategorized,230000,230.0,NaN,110.0
4,4,chr1,5632500,5637500,chr1,5752500,5757500,5635000.0,5745000.0,NaN,NaN,uncategorized,120000,120.0,110.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16594,16594,chrY,11292500,11297500,chrY,11722500,11727500,10645000.0,11540000.0,NaN,NaN,uncategorized,430000,430.0,895.0,NaN
16595,16595,chrY,11522500,11527500,chrY,11712500,11717500,11335000.0,11540000.0,NaN,NaN,uncategorized,190000,190.0,205.0,NaN
16596,16596,chrY,11525000,11530000,chrY,11680000,11685000,11335000.0,11540000.0,NaN,NaN,uncategorized,155000,155.0,205.0,NaN
16597,16597,chrY,11530000,11535000,chrY,11760000,11765000,11335000.0,11540000.0,11750000.0,12900000.0,intra-TAD,230000,230.0,205.0,1150.0
16598,16598,chrY,19432500,19437500,chrY,20742500,20747500,19435000.0,19740000.0,NaN,NaN,uncategorized,1310000,1310.0,305.0,NaN

In [5]:
key_cols = ["chr1", "start1", "end1", "chr2", "start2", "end2"]

# Keep only the columns you need
ctrl_features = ctrl_df[key_cols + ["loop_class"]].copy()
rbp1_features = rbp1_df[key_cols + ["loop_class"]].copy()

# Add a source tag to distinguish them
ctrl_features["source"] = "ctrl"
rbp1_features["source"] = "rbp1"

# Concatenate the two DataFrames row-wise
merged_df = pd.concat([ctrl_features, rbp1_features], ignore_index=True)

merged_df

,chr1,start1,end1,chr2,start2,end2,loop_class,source
0,chr1,3912500,3917500,chr1,4592500,4597500,intra-TAD,ctrl
1,chr1,5502500,5507500,chr1,5622500,5627500,intra-TAD,ctrl
2,chr1,5502500,5507500,chr1,5742500,5747500,inter-TAD,ctrl
3,chr1,5632500,5637500,chr1,5742500,5747500,inter-TAD,ctrl
4,chr1,5635000,5640000,chr1,5980000,5985000,uncategorized,ctrl
...,...,...,...,...,...,...,...,...
35630,chrY,11292500,11297500,chrY,11722500,11727500,uncategorized,rbp1
35631,chrY,11522500,11527500,chrY,11712500,11717500,uncategorized,rbp1
35632,chrY,11525000,11530000,chrY,11680000,11685000,uncategorized,rbp1
35633,chrY,11530000,11535000,chrY,11760000,11765000,intra-TAD,rbp1
35634,chrY,19432500,19437500,chrY,20742500,20747500,uncategorized,rbp1

In [6]:
merged_ml = pd.read_csv("/usr/users/papantonis1/aman/microc_project/loop_calling_premade_hic/jupyter_notes/merged_loops.csv")
merged_ml

,chr1,start1,end1,chr2,start2,end2,status,ctrl_signal,rbp1_signal,log2FC,log2FC_clipped,condition,distance,loop_id,comp_switch_A1,comp_switch_A2
0,chr1,1952500,1957500,chr1,2042500,2047500,shared,NaN,NaN,0.000000,0.000000,shared,90000,0,NaN,NaN
1,chr1,2202500,2207500,chr1,2382500,2387500,shared,NaN,NaN,0.000000,0.000000,shared,180000,1,NaN,NaN
2,chr1,2412500,2417500,chr1,2552500,2557500,shared,NaN,NaN,0.000000,0.000000,shared,140000,2,NaN,NaN
3,chr1,3490000,3495000,chr1,3615000,3620000,shared,NaN,NaN,0.000000,0.000000,shared,125000,3,NaN,NaN
4,chr1,3565000,3570000,chr1,3615000,3620000,shared,NaN,NaN,0.000000,0.000000,shared,50000,4,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32272,chrY,10945000,10950000,chrY,11290000,11295000,gained,0.006078,0.006342,0.061177,0.061177,Mutant loop,345000,32272,stable,stable
32273,chrY,10982500,10987500,chrY,11292500,11297500,gained,0.007661,0.005159,-0.570544,-0.570544,Mutant loop,310000,32273,stable,stable
32274,chrY,11292500,11297500,chrY,11722500,11727500,gained,0.001017,0.001021,0.005836,0.005836,Mutant loop,430000,32274,stable,stable
32275,chrY,11530000,11535000,chrY,11760000,11765000,gained,0.004674,0.006621,0.502513,0.502513,Mutant loop,230000,32275,stable,stable
32276,chrY,19432500,19437500,chrY,20742500,20747500,gained,0.007706,0.016045,1.058072,1.058072,Mutant loop,1310000,32276,stable,stable

In [10]:
# merge
merged_df_dedup = merged_df.drop_duplicates(subset=key_cols)
merged_tad = merged_ml.merge(merged_df_dedup, on=key_cols, how="left")

In [11]:
assert len(merged_tad) == len(merged_ml)
merged_tad["loop_class"].value_counts(dropna=False)

loop_class
intra-TAD        19346
inter-TAD         6543
uncategorized     6388
Name: count, dtype: int64

In [12]:
merged_tad

,chr1,start1,end1,chr2,start2,end2,status,ctrl_signal,rbp1_signal,log2FC,log2FC_clipped,condition,distance,loop_id,comp_switch_A1,comp_switch_A2,loop_class,source
0,chr1,1952500,1957500,chr1,2042500,2047500,shared,NaN,NaN,0.000000,0.000000,shared,90000,0,NaN,NaN,uncategorized,ctrl
1,chr1,2202500,2207500,chr1,2382500,2387500,shared,NaN,NaN,0.000000,0.000000,shared,180000,1,NaN,NaN,uncategorized,ctrl
2,chr1,2412500,2417500,chr1,2552500,2557500,shared,NaN,NaN,0.000000,0.000000,shared,140000,2,NaN,NaN,uncategorized,ctrl
3,chr1,3490000,3495000,chr1,3615000,3620000,shared,NaN,NaN,0.000000,0.000000,shared,125000,3,NaN,NaN,uncategorized,ctrl
4,chr1,3565000,3570000,chr1,3615000,3620000,shared,NaN,NaN,0.000000,0.000000,shared,50000,4,NaN,NaN,uncategorized,ctrl
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32272,chrY,10945000,10950000,chrY,11290000,11295000,gained,0.006078,0.006342,0.061177,0.061177,Mutant loop,345000,32272,stable,stable,intra-TAD,rbp1
32273,chrY,10982500,10987500,chrY,11292500,11297500,gained,0.007661,0.005159,-0.570544,-0.570544,Mutant loop,310000,32273,stable,stable,intra-TAD,rbp1
32274,chrY,11292500,11297500,chrY,11722500,11727500,gained,0.001017,0.001021,0.005836,0.005836,Mutant loop,430000,32274,stable,stable,uncategorized,rbp1
32275,chrY,11530000,11535000,chrY,11760000,11765000,gained,0.004674,0.006621,0.502513,0.502513,Mutant loop,230000,32275,stable,stable,intra-TAD,rbp1
32276,chrY,19432500,19437500,chrY,20742500,20747500,gained,0.007706,0.016045,1.058072,1.058072,Mutant loop,1310000,32276,stable,stable,uncategorized,rbp1

In [14]:
merged_tad.to_csv("ml_2_multiclassmodel.csv")